<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    }
	}, "grade");
}); 
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}
</script>

<form id="add_student" dojoType="dijit.form.Form" method="post">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
		</script>
				<table width="100%" >
					<tr>
						<td>
						 <div id="mainTabContainer" style="width: 1150px;height: 430px;" dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("STUDENT_INFO");?>" selected="true">
					      	<table  cellspacing="5" style="margin:0 auto;" width="100%">
					      		<tr>
					      			<td  title="ឈ្មោះជាភាសារខ្មែរ"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_kh" name="name_kh" value="" type="text" required="required"></td>	
									<td  title="ឈ្មោះជាភាសារអង់គ្លេស"><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_en" name="name_en" value="" type="text" required="required"></td>
									<td title="បញ្ជូលភេទនិស្សិត"><?php echo $tr->translate("SEX");?>*</td>
									<td>
									    <select tabindex="24" name="sex" id="sex" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">Male</option>
										    <option value="2" label="Deactive">Female</option>
										</select>
									</td>
					      		</tr>
					      		<tr>
									<td title="សញ្ឃាតិ"><?php echo $tr->translate("សញ្ជាតិ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="studen_national" name="studen_national" value="" type="text" ></td>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("DOB");?></td>
									<td><input tabindex="20"  name="date_of_birth" id="date_of_birth" dojoType="dijit.form.DateTextBox"  value="now" type="text"/></td>
									<td title="លេខទូរស័ព្ទ"><?php echo $tr->translate("លេខទូរស័ព្ទ*");?></td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="st_phone" name="st_phone" value="" type="text" required="required" ></td>
					      		</tr>
					      		<tr>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("ទីកន្លែងកំណើត 	");?>*</td>
									<td  colspan="6" >
										<textarea   style="width: 644px;height: 60px !important;"
										tabindex="21" dojoType=""  id="place_of_birth" name="place_of_birth" required="required"></textarea>
									</td>
					      		</tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong>អាសយដ្ធានបច្ខុប្បន្ន</strong></td>
					      		</tr>
					      		<tr>
					      			<td>លេខផ្ទះ</td>
									<td><input  dojoType="dijit.form.TextBox"  id="home_note" name="home_note" value="" ></td>
									<td>លេខផ្លូវ</td>
									<td><input  dojoType="dijit.form.TextBox"  id="way_note" name="way_note" value="" type="text" ></td>
									<td>ភូមិ</td>
									<td><input  dojoType="dijit.form.TextBox"  id="village_note" name="village_note" value="" type="text" ></td>
									
								</tr>
								<tr>								
									<td>ឃុំ/សង្កាត់</td>
									<td><input  dojoType="dijit.form.TextBox"  id="commun_note" name="commun_note" value="" type="text" ></td>
									<td>ស្រុក/ខ័ណ្ឌ</td>
									<td><input  dojoType="dijit.form.TextBox"  id="distric_note" name="distric_note" value="" type="text" ></td>
									<td>ខេត្ត/ក្រុង</td>
									<td>
									<select name="student_province" id="student_province" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->province))foreach ($this->province as $row){?>
											<option value="<?php echo $row['province_id']?>"><?php echo $row['province_kh_name']?></option>
											<?php }?>
										</select>
									</td>
									
								</tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានសិក្សានៅមហាវិទ្យាល័យ</strong></td>
					      		</tr>
					      		<tr>
					      			<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>*</td>
									<td><input  dojoType="dijit.form.TextBox"  id="student_id" name="student_id" value="" type="text" ></td>
									<td><?php echo $tr->translate("DEGREE");?>*</td>
									<td>
										<select name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
											<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
											<option value="<?php echo $row['dept_id']?>"><?php echo $row['en_name']?></option>
											<?php }?>
										</select>
									
									</td>
									<td><?php echo $tr->translate("នៅថ្នាក់ទី");?>*</td>
									<td>
									    <input id="grade" />
									</td>
								</tr>
								<tr>
									<td title="កំរិតភាសា"><?php echo $tr->translate("កំរិតភាសា");?>*</td>
									<td>
									    <select tabindex="24" name="level" id="level" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">Biginer</option>
										    <option value="2" label="Deactive">Free</option>
										</select>
									</td>
									<td><?php echo $tr->translate("SESSION");?>*</td>
									<td>
									    <select tabindex="24" name="session" id="session" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">ព្រឹក</option>
										    <option value="2" label="Deactive">រសៀល</option>
										    <option value="2" label="Deactive">យប់</option>
										    <option value="2" label="Deactive">ចុងសបា្តហ៏</option>
										</select>
									</td>
					      		</tr>
					      		
					      	</table>
					      </div><!-- end tab 1 -->
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("ពត័មានអំពី  មាតាបិតា");?>" selected="false">
					     	<table width="100%" style="margin:0 auto;" cellspacing="5">
					      		<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានឪពុក</strong></td>
								</tr>
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_name_kh" name="fa_name_kh" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_name_en" name="fa_name_en" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("AGE");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="fa_age" name="fa_age" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("សញ្ជាតិ");?></td>
					      			<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="fa_national" name="fa_national" value="" type="text" required="required" ></td>
					      			<td><?php echo $tr->translate("មុខរបរ");?></td>
									<td>
										<select name="fa_job" id="fa_job" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->occupation))foreach ($this->occupation as $row){?>
											<option value="<?php echo $row['occupation_id']?>"><?php echo $row['occu_name']?></option>
											<?php }?>
										</select>
									</td>
									<td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_phone" name="fa_phone" value="" type="text" required="required" ></td>
								</tr>
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានម្ថាយ</strong></td>
								</tr>
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_name_kh" name="mom_name_kh" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_name_en" name="mom_name_en" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("AGE");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="age" name="age" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("សញ្ជាតិ");?></td>
								    <td><input  dojoType="dijit.form.TextBox"  id="mom_nation" name="mom_nation" value="" type="text" ></td>
					      			<td><?php echo $tr->translate("មុខរបរ");?></td>
									<td>
										<select name="mom_job" id="mom_job" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->occupation))foreach ($this->occupation as $row){?>
											<option value="<?php echo $row['occupation_id']?>"><?php echo $row['occu_name']?></option>
											<?php }?>
										</select>
									</td>
									<td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mon_phone" name="mon_phone" value="" type="text" required="required" ></td>
								</tr>
					      	</table>
					      	<table frame="box" width="100%" style="margin:0 auto; border:1px solid #ccc;" cellspacing="5">
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានអំពី មាតាបិតា ឬអណាព្យាបាល សម្រាប់ទំនាក់ទំនង</strong></td>
								</tr>
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="guardian_name_kh" name="guardian_name_kh" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="guardian_name_en" name="guardian_name_en" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("AGE");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="guardian_age" name="guardian_age" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("សញ្ជាតិ");?></td>
								    <td><input tabindex="15" dojoType="dijit.form.TextBox"  id="guardian_national" name="guardian_national" value="" type="text" required="required" ></td>
					      			<td><?php echo $tr->translate("លេខអត្តសញ្ញាណប័ណ្ណ  / លិខិតឆ្លងដែន");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="guardian_identity" name="guardian_identity" value="" type="text" required="required" ></td>
					      			<td><?php echo $tr->translate("មុខរបរ");?></td>
									<td>
										<select name="guardian_job" id="guardian_job" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->occupation))foreach ($this->occupation as $row){?>
											<option value="<?php echo $row['occupation_id']?>"><?php echo $row['occu_name']?></option>
											<?php }?>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="guardian_phone" name="guardian_phone" value="" type="text" required="required" ></td>
									<td><?php echo $tr->translate("អ៊ីម៉ែល");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="guardian_email" name="guardian_phone" value="" type="text" required="required" ></td>
								</tr>
										<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong>អាសយដ្ធានបច្ខុប្បន្ន</strong></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("លេខផ្ទះ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="guardian_home" name="guardian_home" value="" ></td>
									<td><?php echo $tr->translate("លេខផ្លូវ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="guardian_way" name="guardian_way" value="" type="text" ></td>
									<td><?php echo $tr->translate("ភូមិ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="guardian_village" name="guardian_village" value="" type="text" ></td>
									
								</tr>
								<tr>								
									<td><?php echo $tr->translate("ឃុំ/សង្កាត់");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="guardian_commun" name="guardian_commun" value="" type="text" ></td>
									<td><?php echo $tr->translate("ស្រុក/ខ័ណ្ឌ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="guardian_distric" name="guardian_distric" value="" type="text" ></td>
									<td><?php echo $tr->translate("ខេត្ត/ក្រុង");?></td>
									<td>
										<select name="guardian_province" id="guardian_province" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->province))foreach ($this->province as $row){?>
											<option value="<?php echo $row['province_id']?>"><?php echo $row['province_kh_name']?></option>
											<?php }?>
										</select>
									</td>
									
								</tr>
							 	
							</table>
							
					      </div>
					       <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("SERVICES");?>" selected="false">
					     	<table width="100%" style="margin:0 auto;" cellspacing="5">
					      		<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានកីឡា</strong></td>
								</tr>
					      		<tr>
									<td ><input  dojoType="dijit.form.CheckBox"  id="check_ka" name="check_ka" value=""  ><?php echo $tr->translate("ការ៉ាតេដូ");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_football" name="check_football" value=""  ><?php echo $tr->translate("បាល់ទាត់");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="ckeck_bos" name="ckeck_bos" value=""  ><?php echo $tr->translate("បាល់បោះ");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_swim" name="check_swim" value=""  ><?php echo $tr->translate("ហែលទឹក");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_hockey" name="check_hockey" value=""  ><?php echo $tr->translate("វាយកូនបាល់");?></td>
					      		    <td ><input  dojoType="dijit.form.CheckBox"  id="check_table" name="check_table" value=""  ><?php echo $tr->translate("រាយកូនឃ្លីលើតុ");?></td>
					      		</tr>
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ជំនាញបំណិនជីវិត</strong></td>
								</tr>
					      		<tr>
									<td ><input  dojoType="dijit.form.CheckBox"  id="check_arts" name="check_arts" value="" type="CheckBox"><?php echo $tr->translate("គេហកិច្ច-អប់រំសិល្បៈ");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_paint" name="check_paint" value=""  ><?php echo $tr->translate("គំនូរ និងហត្ថកម្ម");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="ckeck_music" name="ckeck_music" value=""  ><?php echo $tr->translate("តូរ្យតន្ត្រី");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_dance" name="check_dance" value=""  ><?php echo $tr->translate("សិស្បៈរបាំ");?></td>
					      		</tr>
					            <tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានឡាន</strong></td>
								</tr>
					      		<tr>
									<td ><input  dojoType="dijit.form.CheckBox"  id="check_fee" name="check_fee" value="" type="CheckBox"><?php echo $tr->translate("ADMIN_FEE");?></td>
									<td><input  dojoType="dijit.form.CheckBox"  id="check_car" name="check_car" value=""  ><?php echo $tr->translate("CAR");?></td>
									<td colspan="3">
									    <select tabindex="24" name="type_car" id="type_car" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">Camary</option>
										    <option value="2" label="Deactive">Torise</option>
										    <option value="2" label="Deactive">Corola</option>
										    <option value="2" label="Deactive">Lan</option>
										</select>
									</td>
									<td></td>
									<td></td>
									<td></td>
					      		</tr>
					      	</table>
					      </div>
					   </div>
					   </td>
					</tr>
					<tr>
						<td align="center">
					   				<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
					   	</td>
					  </tr>
					  </table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_major" >
		<form id='frm_major' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>មហាវិទ្យាល័យ</td>
				<td><input dojoType="dijit.form.TextBox"  id="facultyid" name="facultyid" value="" type="hidden">
				<input dojoType="dijit.form.TextBox" readonly="readonly"  id="lbl_faculty" name="lbl_faculty" value="" type="text"></td>
				</td>
			</tr>
			<tr>
				<td>ជំនាញ/EN</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_en" name="major_en" value="" type="text"></td>
			</tr>
			<tr>
				<td>ជំនាញ/KH</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_kh" name="major_kh" value="" type="text"></td>
			</tr>
			<tr>
				<td>អក្សរកាត់</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" class=" fullside height-text" missingMessage="ភ្លេច​បំពេញ​ពាក្យកាត់!" id="shortcut" name="shortcut" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewMajor();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_situation" >
		<form id='frm_situation' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>វណ្ណៈក្នុងគ្រួសារ</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_situation" name="txt_situation" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addsituation();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_composition" >
		<form id='frm_composition' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>សមាសភាពនិស្សិត</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="occu_name" name="occu_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addcomposition();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_school" >
		<form id='frm_school' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ខេត្ត/រាជធានី</td>
				<td><input dojoType="dijit.form.TextBox" readonly="readonly" id="from_province" name="from_province" value="" type="text">
					<input dojoType="dijit.form.TextBox" id="province" name="province" value="" type="text">
				</td>
			</tr>
			<tr>
				<td>ឈ្មោះសាលា</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="school_name" name="school_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addschool();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_scholarship" >
		<form id='frm_scholarship' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ឈ្មោះអាហារូបការណ៏</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_scholarship" name="txt_scholarship" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addscholarship();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
