
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('សិស្សដែលចុះឈ្មោះ')); 
	echo $this->headTitle(''); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width:60%">
	  <tr> 
		<td> <input dojoType="dijit.form.TextBox"   id=adv_search name="adv_search" placeholder="Search by student name....." value="" type="text"></td>
		<td> <input dojoType="dijit.form.DateTextBox" class="fullside" id="start_date" name="start_date" value="<?php  if(empty($this->adv_search['start_date'])){echo date('Y-m-d');}else   echo $this->adv_search['start_date']; ?>"  type="text"></td>
 		<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" value="<?php if(empty($this->adv_search['end_date'])){ echo date('Y-m-d');}else echo $this->adv_search['end_date'];?>" type="text"></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	  </tr>
	 </table>
</form>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<?php echo $this->list;?>
</form>
