<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD STUDENT CHANGE GROUP')); 
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD STUDENT CHANGE GROUP");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td ><?php echo $tr->translate("លេខកូដសិស្ស")?></td>
										<td>
											<select class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
										    	<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
													<option value="<?php echo $row['stu_id']?>"><?php echo $row['stu_code']?></option>
												<?php }?>
											</select>
										</td>
										
										
										<td align="right"><?php echo $tr->translate("ឈ្មោះសិស្ស")?></td>
										<td ><input dojoType="dijit.form.TextBox" readonly="readonly" class="fullside" id="studentname" name="studentname" value="" type="text">
										</td>
									 
									 
										<td align="right"><?php echo $tr->translate("ភេទ")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect"  readonly="readonly" class="fullside" id="gender" name="gender" type="text">
												<option value="1">Male</option>
												<option value="2">Female</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("FROM GROUP")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="from_group" name="from_group" type="text" onchange="toStudentGroup(1);">
												<?php if(!empty($this->row))foreach ($this->row as $_row){?>
													<option value="<?php echo $_row['id']?>"><?php echo $_row['group_code']?></option>
												<?php }?>
											</select>
										</td>
									
										<td align="right"><?php echo $tr->translate("DETAIL")?></td>
										<td  colspan="3" rowspan="1"><label id="lblfromgroup" name="detail_from_group" style="background:#fff;width:100%;height:70px;display:block;"></label></td>
									</tr>
									
									<tr>
										<td><?php echo $tr->translate("TO GROUP")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="to_group" name="to_group" type="text" onchange="toStudentGroup(2);">
												<?php if(!empty($this->row))foreach ($this->row as $_row){?>
													<option value="<?php echo $_row['id']?>"><?php echo $_row['group_code']?></option>
												<?php }?>
											</select>
										</td>
									
										<td align="right"><?php echo $tr->translate("DETAIL")?></td>
										<td  colspan="3" rowspan="1"><label id="lbltogroup" name="detail_to_group" style="background:#fff;width:100%;height:70px;display:block;"></label></td>
									</tr>
									
									
									<tr>
										<td><?php echo $tr->translate("Moving Date")?></td>
										<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="moving_date" name="moving_date" value="1-26-2016" type="text"></td>
									
										<td align="right"><?php echo $tr->translate("NOTE")?></td>
										<td>
											<input dojoType="dijit.form.TextBox" required="true" class="fullside" id="note" name="note" type="text" />
												
										</td>
									
										<td align="right"><?php echo $tr->translate("STATUS")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">
												<option value="1">Active</option>
												<option value="0">Deactive</option>
											</select>
										</td>
									</tr>
									
									
									<tr>
										<td colspan="6" align="center">
										<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script type="text/javascript">
var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-student')); ?>';
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			dojo.xhrPost({
				url:url_student,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data.stu_enname);
					dijit.byId("studentname").attr("value",data.stu_enname);
					dijit.byId("gender").attr("value",data.sex);

				},
				error: function(err) {
					alert(err);
				}
			});
}

var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	//alert(type);
	if(type==1){
		togroup = dijit.byId('from_group').get('value');
	}else{
		togroup = dijit.byId('to_group').get('value');
		}
	
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);

			if(type==1){
				dojo.byId('lblfromgroup').innerHTML='<span style="color:red;">Academic :  </span>'+data.from_academic+'-'+data.to_academic+'<span style="color:red;">  Degree :  </span>'+data.degree+'<span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;">  Session :  </span>'+data.session+"<br />"+'<span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;">  Expired Date :  </span>'+data.expired_date;
			}else{
				dojo.byId('lbltogroup').innerHTML='<span style="color:red;">Academic :  </span>'+data.from_academic+'-'+data.to_academic+'<span style="color:red;">  Degree :  </span>'+data.degree+'<span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;">  Session :  </span>'+data.session+"<br />"+'<span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;">  Expired Date :  </span>'+data.expired_date;
			}
				//dijit.byId("from_detail").attr("value",);
			//dijit.byId("gender").attr("value",data.to_academic);
			

		},
		error: function(err) {
			alert(err);
		}
	});
}





</script>

