<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_GROUP_STUDENT_CHANGE_GROUP')); 
	
	//$hour=explode(',', $this->rs['array_checkbox']);
	//$hour=$this->rs['array_checkbox'];
	//print_r($hour);exit();
	
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("EDIT_GROUP_STUDENT_CHANGE_GROUP");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td width="60%" align="center" valign="top">
								<table cellspacing="10" width="100%"​ style="border: 1px solid #ccc;">
									<tr>
										<td><?php echo $tr->translate("FROM_GROUP")?></td>
										<td >
											<select dojoType="dijit.form.FilteringSelect" required="required"  class="fullside" id="from_group" name="from_group" type="text" onchange="toStudentGroup(1);getStudentFromGroup();">
												<option value="0" placeholder="select group">Select Year </option>
												<?php if(!empty($this->row))foreach ($this->row as $_row){?>
													<option value="<?php echo $_row['id']?>"<?php if($_row['id']==$this->rs['from_group']) echo 'selected="selected"';?>><?php echo $_row['group_code']?></option>
												<?php }?>
											</select>
										</td>
									</tr>
									
									<tr>
										<td align="left"><?php echo $tr->translate("DETAIL")?></td>
										<td ><label id="lblfromgroup" readonly="readonly" name="detail_from_group" style="background:#fff;width:100%;height:70px;display:block;"></label></td>
									</tr>
									
									<tr style="max-height: 100px;height: 100px;overflow: scroll;">
										<td colspan="2" > <div id="data_table" style="height: 300px !important;overflow: scroll;"> </div> </td>
									</tr>
								</table>
							</td>	
							
							<td width="40%" align="center" valign="top">
								<table cellspacing="10" width="100%"​ style="border: 1px solid #ccc;">
									<tr>
										<td align="right"><?php echo $tr->translate("TO_GROUP")?></td>
										<td >
											<select dojoType="dijit.form.FilteringSelect" required="required" class="fullside" id="to_group" name="to_group" type="text" onchange="toStudentGroup(2);">
												<?php if(!empty($this->row))foreach ($this->rows as $_row){?>
													<option value="<?php echo $_row['id']?>" <?php if($_row['id']==$this->rs['to_group']) echo 'selected="selected"';?>><?php echo $_row['group_code']?></option>
												<?php }?>
											</select>
											<input type="hidden" name="old_to_group" id="old_to_group" value="<?php echo $this->rs['to_group'];?>" />
										</td>
									</tr>
									
									<tr>
										<td align="right"><?php echo $tr->translate("DETAIL")?></td>
										<td  ><label id="lbltogroup" readonly="readonly" name="detail_to_group" style="background:#fff;width:100%;height:70px;display:block;"></label></td>
									</tr>
									
									
									<tr style="white-space: nowrap;">
										<td><?php echo $tr->translate("MOVING_DATE")?></td>
										<td>
											<input  dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="moving_date" name="moving_date" value="<?php echo $this->rs['moving_date'];?>" type="text">
										</td>
									</tr>
									<tr style="white-space: nowrap;">
										<td align="right"><?php echo $tr->translate("NOTE")?></td>
										<td>
											<input dojoType="dijit.form.TextBox" class="fullside" value="<?php echo $this->rs['note'];?>" id="note" name="note" type="text" />
										</td>
									</tr>
									
									<tr style="white-space: nowrap;">
										<td align="right"><?php echo $tr->translate("STATUS")?></td>
										<td>
											<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">
												<option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>>Active</option>
												<option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>>Deactive</option>
											</select>
											<input dojoType="dijit.form.TextBox"  type="hidden" name="identity" id="identity" value="" />
										</td>
									</tr>
									
									<tr>
										<td colspan="2" align="center">
											<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
											<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
											 iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"groupstudentchangegroup",'action'=>'index'),null,true); ?>';" />
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>	
									<?php $test=""; foreach ($this->studentpass as $id => $rs){?>
										<input type="hidden" name="old_student<?php echo $id?>" id="old_student<?php echo $id?>" value="<?php echo $rs['stu_id']?>"/>
										<?php if($id==0){$test.=$id;}else{$test.=','.$id;}?>
										
									<?php }?>	
										<input type="hidden" name="old_iden" id="old_iden" value="<?php echo $test;?>"/>
								</table>
							</td>	
							
													
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script type="text/javascript">

dojo.ready(function(){
	var test = '<?php echo $this->rs['array_checkbox'];?>';
	toStudentGroup(1);
	toStudentGroup(2);
	getStudentFromGroup(test);
});

var url_get_all_student_from_group_update = "<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-all-student-update')); ?>";
function getStudentFromGroup(test1){
		//alert(test1);
		var arr = test1.split(',');

		from_group = dijit.byId('from_group').get('value');
		dojo.xhrPost({
			url:url_get_all_student_from_group_update,
			content:{
				'from_group':from_group
				},
			handleAs:"json",
			load: function(respone) {
				tem='<table class="collape tablesorter" style="font-size:12px;background-color:white;width: 99.5%;"  id="table">'
					+'<thead><tr ><th class="tdheader"><?php echo $tr->translate('NUM');?></th>'
						+'<th class="tdheader"><?php echo $tr->translate('CODE');?></th>'
						+'<th class="tdheader"><?php echo $tr->translate('NAME_KH');?></th>'
						+'<th class="tdheader"><?php echo $tr->translate('NAME_EN');?></th>'
						+'<th class="tdheader" colspan="2"><?php echo $tr->translate('SEX');?></th>'
						+'<th style="white-space:nowrap; border-right: 0px none;" class="tdheader" colspan="1"><input style="height: 13px;" type="checkBox" value="0"   name="checkall" onclick="check('+respone.length+');setValue('+respone.length+');" id="checkall"/></th>'
						+'<th style="white-space:nowrap;border-left: 0px none;" class="tdheader" > <?php echo $tr->translate('CHECK_ALL');?></th></tr>'
					+'</thead>';
				if(respone!=""){
					num=0;
					for(var i=0;i<respone.length;i++){
						inx = i+1;
							tem += '<tr>';
						    tem += '<td align="center">&nbsp;'+inx+'&nbsp;<input type="hidden" name="stu_id_'+inx+'" id="stu_id_'+inx+'" value="'+respone[i].stu_id+'" /></td>';
							tem += '<td>&nbsp;<label style="font-size:11px;">'+respone[i].stu_code+'</label></td>';
							tem += '<td>&nbsp;<label style="font-size:11px;">'+respone[i].stu_khname+'</label></td>';
							tem += '<td>&nbsp;<label style="font-size:11px;">'+respone[i].stu_enname+'</label></td>';
							tem += '<td colspan="2" align="center">&nbsp;<label style="font-size:11px;">'+respone[i].sex+'</label></td>';
							tem += '<td align="center" colspan="2"><input style="height: 13px;" type="checkBox"  name="checkbox'+inx+'" id="checkbox'+inx+'"/></td>';
							
							tem += '</tr>';
						    if($("#identity").val()!="") {
								var identity = $("#identity").val();
								$("#identity").val(identity+','+inx);
							} else { $("#identity").val(inx);}
						    
					}
				}
				tem+='</table>';
				dojo.byId('data_table').innerHTML = tem;setpassstudent();
				
			},
			error: function(err) {
				alert(err);
			}
		});
}
function setpassstudent(){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=1;i<=arrays.length;i++) {
		var stu_id = $("#stu_id_"+i).val();
		//alert(iden);
		var pass_identity = $('#old_iden').val();
		var arr = pass_identity.split(',');
		
		for(var j=0;j<arr.length;j++) {
			var pass_stu_id = $("#old_student"+j).val();
			//alert(stu_id);alert(pass_stu_id);
			if(stu_id==pass_stu_id){
				$('#checkbox'+i).prop('checked', true);
				
			}
		}
	}
	
}



function check(i){
	if(dojo.byId('checkall').checked){
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).attr('checked', 'checked');
		}
	}else{
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).removeAttr("checked");
		}
	}
}

var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	//alert(type);
	if(type==1){
		togroup = dijit.byId('from_group').get('value');
	}else{
		togroup = dijit.byId('to_group').get('value');
		}
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);

			if(type==1){
				dojo.byId('lblfromgroup').innerHTML='<span style="color:red;">Academic :  </span>'+data.year+'<span style="color:red;">  Degree :  </span>'+data.degree+'<span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;">  Session :  </span>'+data.session+"<br />"+'<span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;">  Expired Date :  </span>'+data.expired_date;
			}else{
				dojo.byId('lbltogroup').innerHTML='<span style="color:red;">Academic :  </span>'+data.year+'<span style="color:red;">  Degree :  </span>'+data.degree+'<span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;">  Session :  </span>'+data.session+"<br />"+'<span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;">  Expired Date :  </span>'+data.expired_date;
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clear(){
	dojo.byId('lblfromgroup').innerHTML='';
	dojo.byId('lbltogroup').innerHTML='';
	dijit.byId("studentid").attr("value",'');
	dijit.byId("from_group").attr("value",'');
	dijit.byId("studentname").attr("value",'');
	dijit.byId("to_group").attr("value",'');
	dijit.byId("moving_date").attr("value",'');
	dijit.byId("note").attr("value",'');
}

</script>
