<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	echo $this->headTitle('SRMS | Student Exam Fundation Year'); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'group','action'=>'rpt-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
		<div id="divprint">
		<table width="100%" style="margin: 0 auto;">
		
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;scroll;overflow-x:scroll;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							<table style="background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
										<strong></strong><br />
										<strong></strong><br />
									</td>
								</tr>
								<tr>
									<td width="20%" align="left">
										<strong>ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
										<strong>ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br /><br ><br ><br >
									</td>
									<td align="center">
										<strong></strong><br />
										<strong></strong><br />
										<strong style="font-family: Tacteing;"></strong><br />
										<strong>របាយការណ៏ Student Group</strong><br />
										<strong></strong><br />
									</td>
									<td width="20%"></td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th >ល.រ</th>
												<th >Group Code</th>
												<th >Room ID</th>
												<th>Academic</th>
												<th >Semester</th>
												<th >Session</th>
												<th >Degree</th>
												<th >Grade</th>
												<th >Amount Mount</th>
												<th >Start Date</th>					
												<th >Expired Date</th>
												<th >Note</th>
												<th >Status</th>
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['group_code'];?></th>
												<th ><?php echo $row['room_name'];?></th>
												<th ><?php echo $row['academic'];?></th>	
												<th ><?php echo $row['semester'];?></th>
												<th ><?php echo $row['session'];?></th>
												<th ><?php echo $row['degree'];?></th>
												<th ><?php echo $row['grade'];?></th>
												<th ><?php echo $row['amount_month'];?></th>
												<th ><?php echo $row['start_date'];?></th>					
												<th ><?php echo $row['expired_date'];?></th>
												<th ><?php echo $row['note'];?></th>
												<th ><?php echo $row['status'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>			
		</div>
</form>