<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    }
	}, "grade");
	//getallGrade();
}); 
//var grade_store  = getDataStorefromJSON('id','name', <?php // print_r(array())?> );
//var url_dept = '<?php // echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	//function getallGrade(){
		//dept_id = dijit.byId('degree').get('value');
			//dojo.xhrPost({
				//url:url_dept,
				//content:{
				//	'dept_id':dept_id
					},
//				handleAs:"json",
//				load: function(data) {
//					//alert(data);
//					grade_store  = getDataStorefromJSON('id','name', data);
//				    dijit.byId('grade').set('store',grade_store);   
//
//				},
//				error: function(err) {
//					alert(err);
//				}
//			});
	}
</script>

<form id="add_student" dojoType="dijit.form.Form" method="post">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
		</script>
				<table width="100%" >
					<tr>
						<td>
						 <div id="mainTabContainer" style="width: 1150px;height: 430px;" dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
					      <div  class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("ការចុះឈ្មោះចូលរៀន");?>" selected="true">
					      	<table  cellspacing="5" style="margin:0 auto;" width="100%">
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></td>
					      		</tr>
					      		<tr>
					      			<td  title="ឈ្មោះជាភាសារខ្មែរ"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input class="fullside" tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_kh" name="name_kh" value="" type="text" required="required"></td>	
									<td  title="ឈ្មោះជាភាសារអង់គ្លេស"><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input class="fullside"  tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_en" name="name_en" value="" type="text" required="required"></td>
									<td title="បញ្ជូលភេទនិស្សិត"><?php echo $tr->translate("SEX");?>*</td>
									<td>
									    <select class="fullside"  tabindex="24" name="sex" id="sex" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">Male</option>
										    <option value="2" label="Deactive">Female</option>
										</select>
									</td>
					      		</tr>
					      		<tr>
									<td title="សញ្ឃាតិ"><?php echo $tr->translate("សញ្ជាតិ");?></td>
									<td><input class="fullside"  dojoType="dijit.form.TextBox"  id="studen_national" name="studen_national" value="" type="text" ></td>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("DOB");?></td>
									<td><input class="fullside"  tabindex="20"  name="date_of_birth" id="date_of_birth" dojoType="dijit.form.DateTextBox"  value="now" type="text"/></td>
									<td title="លេខទូរស័ព្ទ"><?php echo $tr->translate("លេខទូរស័ព្ទ*");?></td>
									<td><input class="fullside"  tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="st_phone" name="st_phone" value="" type="text" required="required" ></td>
					      		</tr>
					      		<tr>
									<td title="ទីកន្លែងកំណើត"><?php echo $tr->translate("ទីកន្លែងកំណើត ");?>*</td>
									<td  colspan="6" >
										<textarea class="fullside"   style="width: 100%;height: 60px !important;"
										tabindex="21" dojoType=""  id="place_of_birth" name="place_of_birth" required="required"></textarea>
									</td>
					      		</tr>
					      		<tr>
									<td title="អាសយដ្ខានបច្ចុប្បន្ន"><?php echo $tr->translate("អាសយដ្ខានបច្ចុប្បន្ន ");?>*</td>
									<td  colspan="6" >
										<textarea class="fullside"   style="width: 100%;height: 60px !important;"
										tabindex="21" dojoType=""  id="place_of_birth" name="place_of_birth" required="required"></textarea>
									</td>
					      		</tr>
					      		
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានសិក្សានៅមហាវិទ្យាល័យ</strong></td>
					      		</tr>
					      		<tr>
					      			<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>*</td>
									<td><input class="fullside"  dojoType="dijit.form.TextBox"  id="student_id" name="student_id" value="" type="text" ></td>
									<td><?php echo $tr->translate("DEGREE");?>*</td>
									<td>
										<select class="fullside"  name="degree" id="degree" dojoType="dijit.form.FilteringSelect">
											<?php if(!empty($this->serviecename))foreach ($this->serviecename as $row){?>
											<option value="<?php echo $row['service_id']?>"><?php echo $row['title']?></option>
											<?php }?>
										</select>
									</td>
									<td><?php echo $tr->translate("SESSION");?>*</td>
									<td>
										 <select class="fullside"  tabindex="24" name="level" id="level" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="FULL_TIME"><?php echo $tr->translate("FULL_TIME");?></option>
										    <option value="2" label="PART_TIME"><?php echo $tr->translate("PART_TIME");?></option>
										</select>
										
								
									</td>
								</tr>
								<tr>
									<td title="ចាប់ពីម៉ោង"><?php echo $tr->translate("ចាប់ពីម៉ោង");?>*</td>
									<td>
									     <select class="fullside"  tabindex="24" name="from_time" id="from_time" dojoType="dijit.form.FilteringSelect" >
										  <?php $i=0; foreach ($this->hour As $key=>$hour){ $i++;?> 
										    <option value="<?php echo $key?>"><?php echo $hour; ?></option>
										 <?php }?>
										</select>
									</td>
									<td><?php echo $tr->translate("ដល់ម៉ោង");?>*</td>
									<td>
									    <select class="fullside"  tabindex="24" name="to_time" id="to_time" dojoType="dijit.form.FilteringSelect" >
										  <?php $i=0; foreach ($this->hour As $key=>$hour){ $i++;?> 
										    <option value="<?php echo $key?>"><?php echo $hour; ?></option>
										 <?php }?>
										</select>
									</td>
									<td><?php echo $tr->translate("ថ្ងៃចូលរៀន");?></td>
									<td ><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="start_date" name="start_date" value="" type="text"></td>
								
					      		</tr>
					      		<tr>
					      			
					      			<td title="ស្ថានការណ៍"><?php echo $tr->translate("STATUS");?>*</td>
									<td>
										<select class="fullside"  dojoType="dijit.form.FilteringSelect" required="true"  id="status" name="status" type="text">								
											<option value="1" ><?php echo $this->translate("Active")?></option>
											<option value="0" ><?php echo $this->translate("Deactive")?></option>
										</select>
									</td>
					      		</tr>
					      	</table>
					   </div>
					   </td>
					</tr>
					<tr>
						<td align="center">
					   				<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								
					   	</td>
					  </tr>
					  </table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_major" >
		<form id='frm_major' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>មហាវិទ្យាល័យ</td>
				<td><input dojoType="dijit.form.TextBox"  id="facultyid" name="facultyid" value="" type="hidden">
				<input dojoType="dijit.form.TextBox" readonly="readonly"  id="lbl_faculty" name="lbl_faculty" value="" type="text"></td>
				</td>
			</tr>
			<tr>
				<td>ជំនាញ/EN</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_en" name="major_en" value="" type="text"></td>
			</tr>
			<tr>
				<td>ជំនាញ/KH</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_kh" name="major_kh" value="" type="text"></td>
			</tr>
			<tr>
				<td>អក្សរកាត់</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" class=" fullside height-text" missingMessage="ភ្លេច​បំពេញ​ពាក្យកាត់!" id="shortcut" name="shortcut" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewMajor();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_situation" >
		<form id='frm_situation' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>វណ្ណៈក្នុងគ្រួសារ</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_situation" name="txt_situation" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addsituation();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_composition" >
		<form id='frm_composition' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>សមាសភាពនិស្សិត</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="occu_name" name="occu_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addcomposition();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_school" >
		<form id='frm_school' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ខេត្ត/រាជធានី</td>
				<td><input dojoType="dijit.form.TextBox" readonly="readonly" id="from_province" name="from_province" value="" type="text">
					<input dojoType="dijit.form.TextBox" id="province" name="province" value="" type="text">
				</td>
			</tr>
			<tr>
				<td>ឈ្មោះសាលា</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="school_name" name="school_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addschool();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_scholarship" >
		<form id='frm_scholarship' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ឈ្មោះអាហារូបការណ៏</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_scholarship" name="txt_scholarship" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addscholarship();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
