<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_GROUP')); 
	$payment_term = $this->payment_term;
	$rate = $this->rate;
?>	
<head>
 <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
 <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require('dijit.form.Textarea');
    dojo.require("dojo.parser");
    //dojo.require("dijit.form.Select"); 
    //dojo.require("dojo.data.ItemFileWriteStore"); 
	 
</script>
<style>
select{ width:100%;}
fieldset{  background:#DFF7FD;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>

<script type="text/javascript">

dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    }
	}, "grade");
	getallGrade();
	toStudentGroup();
}); 
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentgroup','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   
				    dijit.byId('grade').attr('value','<?php echo $this->value['grade']; ?>');  
					},
				error: function(err) {
					alert(err);
				}
			});
	}

	
</script>
<?php
$frm_set_price = $this->frm_set_charge;?>
<form id='studentgroup' dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentgroup','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong>Search Group</strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
							<tr>
							<td>ឆ្នាំសិក្សា</td>
							<td>
								<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="from_year" name="from_year" type="text">
									<?php for($i=2014;$i<=date('Y')+1;$i++){?>
										<option value="<?php echo $i;?>"><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							<td>ដល់</td>
							<td>
								<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="to_year" name="to_year" type="text">
									<?php for($i=2015;$i<=date('Y')+2;$i++){?>
										<option value="<?php echo $i;?>"><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							<td>Degree</td>
							<td>
								<select class="fullside"  name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
											<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
											<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->value['degree']) echo "selected='selected'"?>><?php echo $row['en_name']?></option>
											<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td>ថ្នាក់ទី*</td>
							<td>
							    <input id="grade" value="<?php echo $this->value['grade'];?>" />
							</td>
							<td>Session</td>
							<td>
								 <select class="fullside"  tabindex="24" name="session" id="session" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" <?php if($this->value['session']==1){{echo "selected='selected'"; }}?> label="morning" >ព្រឹក</option>
										    <option value="2" <?php if($this->value['session']==2){{echo "selected='selected'"; }}?> label="afternoon">រសៀល</option>
										    <option value="3" <?php if($this->value['session']==3){{echo "selected='selected'"; }}?> label="night">យប់</option>
										    <option value="4" <?php if($this->value['session']==4) {{ echo "selected='selected'"; }}?> label="weekend">ចុងសបា្តហ៏</option>
										</select>
							</td>
							<td colspan="2" align="center">
								 	<input type="submit" dojoType="dijit.form.Button"  label="SEARCH" id="search"
								 		iconClass="dijitEditorIcon dijitEditorIconSearch"/>
							</td>
						</tr>
						
					
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<tfoot>
							<tr>
								<td><a id="select-all" href="#">select all</a></td>
								<td><a id="deselect-all" href="#">deselect all</a></td>
								<td><a id="select-100" href="#">select 100 elems</a></td>
								<td><a id="deselect-100" href="#">deselect 100 elems</a></td>
								<td><a id="add-option" href="#">Add option</a></td>
								<td><a id="refresh" href="#">refresh</a></td>
							</tr>
							<tr>
							<td>Group</td>
							<td>
								<select class="fullside"  name="group" id="group" dojoType="dijit.form.FilteringSelect" required="true" type="text" onchange="toStudentGroup();">
											<?php if(!empty($this->group))foreach ($this->group as $row){?>
											<option value="<?php echo $row['id']?>"><?php echo $row['group_code']?></option>
											<?php }?>
								</select>
							</td>
							<td><?php echo $tr->translate("DETAIL")?></td>
							<td  colspan="3" rowspan="1"><label id="lbldetail" name=lbldetail style="background:#fff;width:100%;height:70px;display:block;"></label></td>
						</tr> 
							<tr>
								<td colspan="8">
									<select multiple id="public-methods" name="public-methods[]">
										<?php if(!empty($this->rs)) foreach($this->rs as $row){?>
										<option value="<?php echo $row['stu_id'];?>">
										<?php echo $row['stu_code']," ",$row['stu_enname']," ",$row['stu_khname']; ?></option>
										<?php }?>
									 </select>
								</td>
							</tr>
							<tr>
							<td align="center" colspan="8">
								<input type="submit" dojoType="dijit.form.Button"  label="SAVE" id="save"
								 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
							</td>
							</tr>
						</tfoot>
				 </table>
				 
				 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
   				 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
   				 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-student')); ?>';
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			dojo.xhrPost({
				url:url_student,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data.stu_enname);
					dijit.byId("studentname").attr("value",data.stu_enname);
					dijit.byId("gender").attr("value",data.sex);

				},
				error: function(err) {
					alert(err);
				}
			});
}

var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(){
	//alert(type);
		group = dijit.byId('group').get('value');

	
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':group
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);

				dojo.byId('lbldetail').innerHTML='<span style="color:red;">Academic :  </span>'+data.from_academic+'-'+data.to_academic+'<span style="color:red;">  Degree :  </span>'+data.degree+'<span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;">  Session :  </span>'+data.session+"<br />"+'<span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;">  Expired Date :  </span>'+data.expired_date;
			

		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>


