<?php 
	$frm_student = $this->frm_student;
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
</script>
<form id="add_student" dojoType="dijit.form.Form" method="post">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
		</script>
				<table width="100%">
					<tr>
						<td>
						 <div id="mainTabContainer" style="width: 1150px;height: 430px;" dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("ព័ត៍មានសិស្ស");?>" selected="true">
					      	<table cellspacing="5" style="margin:0 auto;" width="100%" >
					      		<tr>
					      			<td  title="ឈ្មោះជាភាសារខ្មែរ"><?php echo $tr->translate("NAME_KH");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_kh" name="name_kh" value="" type="text" required="required"></td>	
									<td  title="ឈ្មោះជាភាសារអង់គ្លេស"><?php echo $tr->translate("NAME_EN");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="name_en" name="name_en" value="" type="text" required="required"></td>
									<td title="បញ្ជូលភេទនិស្សិត"><?php echo $tr->translate("SEX");?>*</td>
									<td>
									    <select tabindex="24" name="sex" id="sex" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">Male</option>
										    <option value="2" label="Deactive">Female</option>
										</select>
									</td>
					      		</tr>
					      		<tr>
									<td title="សញ្ឃាតិ"><?php echo $tr->translate("សញ្ជាតិ");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="studen_national" name="studen_national" value="" type="text" ></td>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("DOB");?></td>
									<td><input tabindex="20"  name="date_of_birth" id="date_of_birth" dojoType="dijit.form.DateTextBox"  value="now" type="text"/></td>
									<td title="លេខទូរស័ព្ទ"><?php echo $tr->translate("សំបុត្រកំណើត");?></td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="birth_cert_no" name="birth_cert_no" value="" type="text" ></td>
					      		</tr>
					      		<tr>
									<td title="សញ្ឃាតិ"><?php echo $tr->translate("ជាកូនទី");?></td>
									<td>
									    <select tabindex="24" name="position_of_child" id="position_of_child" dojoType="dijit.form.FilteringSelect" >
										    <?php for ($i=1;$i<20;$i++){?>
										    <option value="<?php echo $i;?>"><?php echo $i;?></option>
										    <?php }?>
										</select>​​​​​
									</td>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("នៃចំនួនកូន");?></td>
									<td>
									    <select tabindex="24" name="of_children" id="of_children" dojoType="dijit.form.FilteringSelect" >
										    <?php for ($i=1;$i<20;$i++){?>
										    <option value="<?php echo $i;?>"><?php echo $i;?></option>
										    <?php }?>
										</select>
									</td>
									<td title="លេខទូរស័ព្ទ"><?php echo $tr->translate("NATIVE_LANGUAGE");?></td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="native_language" name="native_language" value="" type="text" ></td>
					      		</tr>
					      		<tr>
									<td title="សញ្ឃាតិ"><?php echo $tr->translate("CURRENT_CARE_GIVER");?></td>
									<td>
									    <select tabindex="24" name="current_car_giver" id="current_car_giver" dojoType="dijit.form.FilteringSelect" >
										    <option value="1">Parents</option>
										    <option value="2">Grandparent</option>
										    <option value="3">Another child</option>
										    <option value="4">Foreign Maid</option>
										</select>​​​​​
									</td>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("OTHER");?></td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="current_other" name="current_other" value="" type="text" ></td>
									<td title="លេខទូរស័ព្ទ"><?php echo $tr->translate("OTHER_SPEAKING_LANGUAGE");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="other_language" name="other_language" value="" type="text" ></td>   
					      		</tr>
					      		<tr>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("ទីកន្លែងកំណើត 	");?>*</td>
									<td  colspan="3" >
										<textarea   style="width: 644px;height: 50px !important;"
										tabindex="21" dojoType=""  id="place_of_birth" name="place_of_birth" required="required"></textarea>
									</td>
									<td><?php echo $tr->translate("MEAL REQUIRED");?></td>
									<td>
									    <select tabindex="24" name="meal_required" id="meal_required" dojoType="dijit.form.FilteringSelect" >
										    <option value="1">No Lunch</option>
										    <option value="2">Lunch</option>
										</select>​​​​​
									</td>
					      		</tr>
					      		<tr>
									<td title="ថ្ងៃខែឆ្នាំកំនើត"><?php echo $tr->translate("អាសយដ្ធានបច្ខុប្បន្ន*");?></td>
									<td  colspan="3" >
										<textarea   style="width: 644px;height: 50px !important;"
										tabindex="21" dojoType=""  id="place_address" name="place_address" required="required"></textarea>
									</td>
					      		</tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong>កម្មវិធីនៃការសិក្សា</strong></td>
					      		</tr>
					      		<tr>
					      			<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>*</td>
									<td><input  dojoType="dijit.form.TextBox"  id="student_id" name="student_id" value="" type="text" ></td>
									<td><?php echo $tr->translate("DEGREE");?>*</td>
									<td><select tabindex="24" name="degree" id="degree" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">K1</option>
										    <option value="2" label="Deactive">K2</option>
										    <option value="2" label="Deactive">K3</option>
										</select>
									</td>
									<td><?php echo $tr->translate("SESSION");?>*</td>
									<td>
									    <select tabindex="24" name="session" id="session" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active">AM</option>
										    <option value="2" label="Deactive">PM</option>
										    <option value="2" label="Deactive">FULL_DAY</option>
										</select>
									</td>
								</tr>
								<tr>
									<td ><?php echo $tr->translate("DATE_OF_ENROLMENT");?></td>
									<td><input tabindex="20"  name="date_of_enrolment" id="date_of_enrolment" dojoType="dijit.form.DateTextBox"  value="now" type="text"/></td>
									<td ><?php echo $tr->translate("OF_ENTRY");?></td>
									<td><input tabindex="20"  name="date_of_entry" id="date_of_entry" dojoType="dijit.form.DateTextBox"  value="now" type="text"/></td>
					      		</tr>
					      	</table>
					      </div><!-- end tab 1 -->
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("ពត័មានអំពី  មាតាបិតា");?>" selected="false">
					     	<table width="100%" style="margin:0 auto;" cellspacing="2">
					      		<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានឪពុក</strong></td>
								</tr>
								<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME_AS_IN_NRIC");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_name_nric" name="fa_name_nric" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("NRIC_NO");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_nric_no" name="fa_nric_no" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("DATE_OF_BIRTH");?></td>
									<td><input tabindex="15" dojoType="dijit.form.DateTextBox"  id="fa_date_of_birth" name="fa_date_of_birth" value="now" type="text" ></td>
					      		</tr>
					      		<tr>
					      		    <td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_phone" name="fa_phone" value="" type="text" required="required" ></td>
									<td ><?php echo $tr->translate("EMAIL_ADDRESS");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="fa_email_address" name="fa_email_address" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("NAME_OF_COMPANY");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="fa_of_company" name="fa_of_company" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("OCCUPATION");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="fa_occupation" name="fa_occupation" value="" type="text" ></td>
									<td width="12%"><?php echo $tr->translate("LANGUAGE_SPOKEN");?>​</td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="fa_language_spoken" name="fa_language_spoken" value="" type="text"></td>
									<td><?php echo $tr->translate("NATIONALITY");?></td>
								    <td>
								        <select tabindex="24" name="fa_nationality" id="fa_nationality" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active"><?php echo $tr->translate("CAMBODIAN_CITIZEN");?></option>
										    <option value="2" label="Deactive"><?php echo $tr->translate("PERMANENT_RESIDENT");?></option>
										    <option value="2" label="Deactive"><?php echo $tr->translate("OTHERS");?></option>
										</select>
								    </td>
								</tr>
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានម្ថាយ</strong></td>
								</tr>
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME_AS_IN_NRIC");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_name_nric" name="mom_name_nric" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("NRIC_NO");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_nric_no" name="mom_nric_no" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("DATE_OF_BIRTH");?></td>
									<td><input tabindex="15" dojoType="dijit.form.DateTextBox"  id="mom_date_of_birth" name="mom_date_of_birth" value="now" type="text" ></td>
					      		</tr>
					      		<tr>
					      		    <td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_phone" name="mom_phone" value="" type="text" required="required" ></td>
									<td ><?php echo $tr->translate("EMAIL_ADDRESS");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="mom_email_address" name="mom_email_address" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("NAME_OF_COMPANY");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="mom_of_company" name="mom_of_company" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("OCCUPATION");?></td>
									<td><input  dojoType="dijit.form.TextBox"  id="mom_occupation" name="mom_occupation" value="" type="text" ></td>
									<td width="12%"><?php echo $tr->translate("LANGUAGE_SPOKEN");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="mom_language_spoken" name="mom_language_spoken" value="" type="text"></td>
									<td><?php echo $tr->translate("NATIONALITY");?></td>
								    <td>
								        <select tabindex="24" name="mom_nationality" id="mom_nationality" dojoType="dijit.form.FilteringSelect" >
										    <option value="1" label="Active"><?php echo $tr->translate("CAMBODIAN_CITIZEN");?></option>
										    <option value="2" label="Deactive"><?php echo $tr->translate("PERMANENT_RESIDENT");?></option>
										    <option value="2" label="Deactive"><?php echo $tr->translate("OTHERS");?></option>
										</select>
								    </td>
								</tr>
					      	</table>
					      </div>
					      <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("TRANSPORTER");?>" selected="false">
					     	<table width="100%" style="margin:0 auto;" cellspacing="3">
					      		<tr>
									<td colspan="4" style="border-bottom:1px solid #ccc;"><strong>ព័ត៏មានអ្នកដឹកជញ្ជូន</strong></td>
								</tr>
								<tr>
					      			<td width="12%"><?php echo $tr->translate("RELATIONSHIP_TO_CHILD");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="tr_relationship_to_child" name="tr_relationship_to_child" value="" type="text" required="required"></td>
									<td><?php echo $tr->translate("NRIC_NO");?></td>
									<td><input tabindex="15" dojoType="dijit.form.TextBox"  id="tr_passport_no" name="tr_passport_no" value="" type="text" ></td>
					      		</tr>
					      		<tr>
					      		    <td ><?php echo $tr->translate("NAME");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="tr_name" name="tr_name" value="" type="text" required="required"></td>
									<td ><?php echo $tr->translate("CONTACT_NO");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="tr_contact_no" name="tr_contact_no" value="" type="text" required="required"></td>
					      		</tr>
								<tr>
									<td colspan="4" style="border-bottom:1px solid #ccc;"><strong>ទំនាក់ទំនងបន្ទាន់(បន្ទាប់ពីមាតាមិតា)</strong></td>
								</tr>
					      		<tr>
					      			<td width="12%"><?php echo $tr->translate("NAME");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="ca_name" name="ca_name" value="" type="text" required="required"></td>
									<td width="12%"><?php echo $tr->translate("RELATIONSHIP_TO_CHILD");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="ca_relationship_to_child" name="ca_relationship_to_child" value="" type="text" required="required"></td>
					      		</tr>
					      		<tr>
					      		    <td ><?php echo $tr->translate("NRIC_NO");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="tr_nric_no" name="tr_nric_no" value="" type="text" required="required"></td>
					      		    <td><?php echo $tr->translate("PHONE");?>*</td>
									<td><input tabindex="15" dojoType="dijit.form.ValidationTextBox"  id="tr_phone" name="tr_phone" value="" type="text" required="required" ></td>
					      		</tr>
					      		<tr>
					      		    <td ><?php echo $tr->translate("ADDRESS");?></td>
									<td colspan="3">
									     <textarea   style="width: 800px;height: 50px !important;"
										    tabindex="21" dojoType=""  id="ca_address" name="ca_address" required="required"></textarea>
									</td>
					      		</tr>
					      	</table>
					      </div>
					   </div>
					   </td>
					</tr>
					<tr>
						<td align="center">
					   				<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
					   	</td>
					  </tr>
					  </table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_major" >
		<form id='frm_major' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>មហាវិទ្យាល័យ</td>
				<td><input dojoType="dijit.form.TextBox"  id="facultyid" name="facultyid" value="" type="hidden">
				<input dojoType="dijit.form.TextBox" readonly="readonly"  id="lbl_faculty" name="lbl_faculty" value="" type="text"></td>
				</td>
			</tr>
			<tr>
				<td>ជំនាញ/EN</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_en" name="major_en" value="" type="text"></td>
			</tr>
			<tr>
				<td>ជំនាញ/KH</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" missingMessage="Invalid Module!" class="full height-text" id="major_kh" name="major_kh" value="" type="text"></td>
			</tr>
			<tr>
				<td>អក្សរកាត់</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" class=" fullside height-text" missingMessage="ភ្លេច​បំពេញ​ពាក្យកាត់!" id="shortcut" name="shortcut" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewMajor();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_situation" >
		<form id='frm_situation' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>វណ្ណៈក្នុងគ្រួសារ</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_situation" name="txt_situation" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addsituation();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_composition" >
		<form id='frm_composition' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>សមាសភាពនិស្សិត</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="occu_name" name="occu_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addcomposition();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_school" >
		<form id='frm_school' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ខេត្ត/រាជធានី</td>
				<td><input dojoType="dijit.form.TextBox" readonly="readonly" id="from_province" name="from_province" value="" type="text">
					<input dojoType="dijit.form.TextBox" id="province" name="province" value="" type="text">
				</td>
			</tr>
			<tr>
				<td>ឈ្មោះសាលា</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="school_name" name="school_name" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addschool();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_scholarship" >
		<form id='frm_scholarship' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td>ឈ្មោះអាហារូបការណ៏</td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="txt_scholarship" name="txt_scholarship" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="រក្សាទុក" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addscholarship();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
