<head>
  <meta charset="utf-8">
  <title>jQuery UI Accordion - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
</head>

<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_FEE')); 
	$payment_term = $this->payment_term;
	 
?>	
 
<script>
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.parser");
dojo.require("dijit.layout.AccordionContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 0px; border:1px solid #ccc;font-size: 12px;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
	//control study year
		var years_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->row_year));?> );
		new dijit.form.FilteringSelect({
		    store:years_store,
		    autoComplete: true,                        
		    required: true,
		    id: "year_study",
		    name: "year_study",           
		    class: 'fullside',  
		    required:'true',
		    placeHolder:"Selected Study Years",          
		    onChange: function() {  
			   
		    	getGroupName();
		    }
		}, "year_study");
		
		var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_group));?> );
		new dijit.form.FilteringSelect({
			store:group_store,
		    autoComplete: true,                        
		    required: true,
		    id: "study_group",
		    name: "study_group",           
		    class: 'fullside',  
		    required:'',
		    placeHolder:"Selected Study Group",          
		    onChange: function() {  
		    	study_group=dijit.byId('study_group').get('value');
		    	//document.getElementById("table_row").innerHTML = '';
		    	getStudentAll();
				  //  getStudent(study_group);
			    getParentName();
		    }
		}, "study_group");

		 var metion = '<?php echo $this->all_metion; ?>';
		 
		 
	});
function getStudentAll(){
	study_group=dijit.byId('study_group').get('value');
	if(study_group !=''){
		getStudentByIdGroup(study_group);
	} 
}
//get parent name filter by group id
function getParentName(){
	group_id=dijit.byId('study_group').get('value');
	if(group_id !=''){
		getParent(group_id);
	}
}
var parent_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_parent = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentscores','action'=>'get-parent-name')); ?>';
function getParent(group_id){
	dojo.xhrPost({
		url:url_parent,
		content:{
			'group_id':group_id,
			},
		handleAs:"json",
		load: function(data) {
			parent_stores  = getDataStorefromJSON('id','name', data);
		 //   dijit.byId('parent_name').set('store',parent_stores);
		},
		error: function(err) {
			  alert(err);
		}
	});
}


//function fileter group name 
function getGroupName(){
	
	academic_id=dijit.byId('year_study').get('value');
	session_id=dijit.byId('session').get('value');
    if(academic_id !=''){
        //alert(academic_id+"-"+session_id);
    	getGroup(academic_id,session_id);
    }
}
var group_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_groupname = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentscores','action'=>'get-group-name')); ?>';
function getGroup(academic_id,session_id){
	dojo.xhrPost({
		url:url_groupname,
		content:{
			'academic_id':academic_id,
			'session_id':session_id
			},
		handleAs:"json",
		load: function(data) {
			if(data !=''){
				group_stores  = getDataStorefromJSON('id','name', data);
			    dijit.byId('study_group').set('store',group_stores);  
			}else{
				dijit.byId('study_group').set('store',group_store);  
				dijit.byId('study_group').attr('value','');  
			}
		},
		error: function(err) {
			  alert(err);
		}
	});
}


//function select student
function getStudent(){
	//dijit.byId('parent_name').attr('value','');
	group_id=dijit.byId('study_group').get('value');
	if(group_id !=''){
		getStudentByIdGroup(group_id);
		
	}else{
		document.getElementById("table_row").innerHTML = '';
	}
}
ccc='';
var url_getStudent= '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentscores','action'=>'get-student')); ?>';
function getStudentByIdGroup(group_id){
	
	dojo.xhrPost({
	    url: url_getStudent,
	    content : { 
		    'group_id':group_id,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		       //alert(data);
		   tem="";
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				    str+='<div id="accordion">';
				for(i=0;i<data.length;i++){
					inx = i+1;
					num++;
					str+='<h3>'+'Student id('+data[i].stu_code+')'+' Student Name('+data[i].stu_khname+')</h3><div>';
					str+='<table>';
                    str+='<tr><td>១.ភាសាខ្មែរ(Khmer)</td><td><input style="width:100px;" dojoType="dijit.form.validateNumberTextBox" class="fullside" name="totale_khmer_'+inx+'" id="totale_khmer_'+inx+'" required="true" value="" type="text"></td></tr>';
	                str+='<tr><td>&nbsp;&nbsp;-ការស្តាប់(Listening)</td><td><input style="width:100px;" dojoType="dijit.form.validateNumberTextBox" class="fullside" name="listening_'+inx+'" id="listening_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">២.គណិតវិទ្យា(Mathematics)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="mathematics_'+inx+'" id="mathematics_'+inx+'" required="true" value="" type="text"></td>';
	                str+='<td style="padding-left: 30px ! important;"> ១.តួរ្យតន្រ្តី(Music)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="music_'+inx+'" id="music_'+inx+'"  value="" type="text"></td></tr>';    

	                str+='<tr><td>&nbsp;&nbsp;-ការនិយាយ(Speaking)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="speaking_'+inx+'" id="speaking_'+inx+'"   value="" type="text"></td>';
	                str+='<td style="padding-left: 30px ! important;">៣.វិទ្យាសាស្រ្តអនុវត្ថ(Sciences)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="sciences_'+inx+'" id="sciences_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;"> ២.សិល្បៈរបាំ(Dance)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="dance_'+inx+'" id="dance_'+inx+'"  value="" type="text"></td></tr>';    

                    str+='<tr><td>&nbsp;&nbsp;-កាអាន(Reading)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="reading_'+inx+'" id="reading_'+inx+'"   value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">៤.ភាសាអង់គ្លេស(English)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="english_'+inx+'" id="english_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;"> ៣.គំនូរ និង ហត្ថកម្ម(Art & Craft)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="art_craft_'+inx+'" id="art_craft_'+inx+'"  value="" type="text"></td></tr>';    

                    str+='<tr><td>&nbsp;&nbsp;-សរសេរតាមអាន(Dictation)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="dictation_'+inx+'" id="dictation_'+inx+'"   value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">៥.កុំព្យូទ័រ(Computer)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="computer_'+inx+'" id="computer_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;"> ៤.គេហកិច្ច-អប់រំសិល្បៈ(Home Economic)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="home_economic_'+inx+'" id="home_economic_'+inx+'"  value="" type="text"></td></tr>';    

                    str+='<tr><td>&nbsp;&nbsp;-តែងសេចក្តី(Composition)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="composition_'+inx+'" id="composition_'+inx+'"   value="" type="text"></td> ';
                    str+='<td style="padding-left: 30px ! important;">៦.អប់រំកាយ-សុខភាព(PE / Health)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="pe_health_'+inx+'" id="pe_health_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;"> ៥.កីឡា(Sport)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="sport_'+inx+'" id="sport_'+inx+'"  value="" type="text"></td></tr>';    

                    str+='<tr><td>&nbsp;&nbsp;-អក្សរផ្ចង់(Calligraphy)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="calligraphy_'+inx+'" id="calligraphy_'+inx+'"   value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">អវត្តមានមានច្បាប់ / Absence with Permission</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="absence_with_permission_'+inx+'" id="absence_with_permission_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">អវត្តមានអត់ច្បាប់ / Absence without Permission</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="absence_without_per_'+inx+'" id="absence_without_per_'+inx+'" required="true" value="" type="text"></td></tr>';
                    
                    str+='<tr><td>៧.សិក្សាសង្គម(Social Studies)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="social_studies_'+inx+'" id="social_studies_'+inx+'"   value="" type="text"></td></tr>';
                    str+='<tr><td>&nbsp;&nbsp;-សីលធម៍-ពលរដ្ឋវិជ្ជា(Moral/Civics)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="moral_civics_'+inx+'" id="moral_civics_'+inx+'" required="true" value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">អវត្តមានសរុប / Total Absence(s)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="total_bsence_'+inx+'" id="total_bsence_'+inx+'"   value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">ពិន្ទុសរុប / Total score</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="total_score_'+inx+'" id="total_score_'+inx+'"   value="" type="text"></td>';
                     str+='</tr>';

                    str+='<tr><td>&nbsp;&nbsp;-ភូមិវិទ្យា(Geography)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="geography_'+inx+'" id="geography_'+inx+'"  value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">មធ្យមភាគប្រចាំខែ /Monthly Average</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="monthly_average_'+inx+'" id="monthly_average_'+inx+'"   value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">និទ្ទេស / Letter Grade </td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="letter_grade_'+inx+'" id="letter_grade_'+inx+'"   value="" type="text"></td>';
                    str+='</tr>';

                    str+='<tr><td>&nbsp;&nbsp;-ប្រវត្តិវិទ្យា(History)</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="history_'+inx+'" id="history_'+inx+'"  value="" type="text"></td>';
                    str+='<td style="padding-left: 30px ! important;">ចំណាត់ថ្នាក់ / Rank</td><td><input style="width:100px;" dojoType="dijit.form.TextBox" class="fullside" name="rank_'+inx+'" id="rank_'+inx+'"  value="" type="text"></td>';
                    str+='<td></td><td></td>';
                    str+='</tr>';
					str+='</table>';
					str+='</div>';
				    if(inx!=1) {//identity set value 1,2,3,4,5
						var identity = $('#identity').val();
						$('#identity').val(identity+','+inx);
					} else {
						$('#identity').val(inx);
					}
				}
				str+='</div>';
				document.getElementById("liststudent").innerHTML = str;
				 $( "#accordion" ).accordion();
	       }else{
	    	   $('#identity').val('');
	       }
	   },		
	    error: function(err) {
		 //   alert(err);
	    }
	});
	
}
function gender(sex){
	if(sex==1){
		sex='ប្រុស';
	}else sex='ស្រី';
	return sex;
}
</script>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentscores','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center" style="font-size: 14px;"><strong><?php echo $tr->translate("ADD_NEW_STUDENT_SCORE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td  ><?php echo $tr->translate("STUDY_YEAR");?></td>
							<td>
								<input id="year_study" />
							</td>
							<td  ><?php echo $tr->translate("SESSION");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside"  id="session" name="session" type="text" onChange="getGroupName();">
								  <?php if(!empty($this->row_sesion)) foreach($this->row_sesion As $rs_sesion){?>
									<option value="<?php echo $rs_sesion['key_code']?>"><?php echo  $rs_sesion['view_name'];?></option>
								  <?php }?> 
								</select>
							</td>
							<td  ><?php echo $tr->translate("STUDENT_GROUP");?></td>
							<td>
								<input id="study_group" />
							</td>
							
						</tr>
						
						<tr>
							<td  ><?php echo $tr->translate("TERM");?></td>
							<td align="center">
								<select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside"  id="term" name="term" type="text">
									<?php for($i=1;$i<=6;$i++){?>
									<option value="<?php echo $i;?>"><?php echo $i;?></option>
									<?php }?>
								</select>
							</td>
						    <td style="white-space: nowrap;text-align: right;"><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
										<option value="1">ប្រើប្រាស់</option>
										<option value="0">មិនប្រើប្រាស់</option>
								</select>
							</td>	
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td colspan="8">
							<labal id="liststudent">
							</labal>
							</td>
						</tr>
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="hidden" label="<?php echo $tr->translate('ADD_ROW');?>"  
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 	<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
									<?php $id++;if($i==0)$term = $id;
									else{$term.=','.$id;} ?>
								<?php }?>
									<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
									<input type="text" name="identity" id="identity"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
							          	<tr id="head-title" class="head-td" align="right"></tr>
							         </table>
								</td>
							</tr>
							 
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
								 	<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<?php $frm_dept = $this->add_dept;?>

<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}

function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var faculty = '<?php echo $this->all_faculty; ?>';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
//var pay_term ="<?php //print_r($payment_term);?>";

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_ID");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_NAME");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_GRADE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_SCORE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="4%" align="center">'+no+'</td>';
			template+='<td style="width:200px;padding-left:10px;">01111</td>';	
			template+='<td style="width:200px;padding-left:10px;">Meas Dara </td>';		
			template+='<td style="width:200px;padding-left:10px;">K1</td>';
			template+='<td><input style="width:200px;padding-left:10px;" dojoType="dijit.form.NumberTextBox" class="fullside" name="studentscore_'+col+'" id="studentscore_'+col+'" value="" type="number"></td>';
			template+='<td><input style="width:200px;padding-left:10px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(template);
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	
		  

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		
 }

var url_get_faculty ='<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'getfaculty-option')); ?>';
function getAllFucaltyOption(f_id){                                                                      
	dojo.xhrPost({
		url: url_get_faculty,				    
		handleAs:"json", 
		load: function(response){
			//alert(response.option);
			dojo.html.set(dojo.byId("lbl_metion"+r_index),'',{
			     parseContent: true});
			faculty=response.option;
			    select='<select class="full" dojoType="dijit.form.FilteringSelect" name="metion'+r_index+'" id="metion'+r_index+'" >'+faculty+'</select>';
				dojo.html.set(dojo.byId("lbl_metion"+r_index),select, {
				     parseContent: true
				});
				dijit.byId("metion"+r_index).attr( 'value',f_id);
				alert('<?php echo $tr->translate("INSERT_SUCCESS"); ?>');
				//dijit.byId('frm_service').reset();
		},error:function(err){
			alert(err);
		}
	});
}

 
//////bong 
function getSubjectByParent(){
	temp="";
	 
	dojo.xhrPost({
		url:url_getSubject,
		content:{
			'parent_id':parent_id
			},
		handleAs:"json",
		load: function(data) {
			array = data.length;
			for(var k=0;k<data.length;k++) {
				temp+='<th>'+data[k].name+'</th>';
				tem+='<td>&nbsp;<input style="width:240px;padding-left:10px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+k+'" id="note_'+k+'" value="" type="text"></td>';
			}
		//	document.getElementById('sub_subject').innerHTML = temp;
			document.getElementById('text_score').innerHTML = tem;
		},
		error: function(err) {
			 //alert(err);
		}
	});
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>