<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('ADD_DEGREE_LANGUAGE')); 
	echo $this->headTitle(''); 
	
?>	

<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>

<form id="add_language" dojoType="dijit.form.Form" method="post" >
		<table cellspacing="10" width="50%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate("ADD_DEGREE_LANGUAGE");?></legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("LANGUAGE_LEVEL")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="language_title" id="language_title" type="text" required="required" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISCRIPTION")?></td>
							<td>
								<textarea class="fullside"   style=" height: 60px !important;"
										tabindex="2" dojoType=""  id="note" name=note ></textarea>
									
							</td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("STATUS")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="status_p" id="status_p" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("Active")?></option>
									    <option value="0"><?php echo $tr->translate("Deactive")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" value="back" label="<?php echo $tr->translate("GO_BACK")?>" dojoType="dijit.form.Button" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"language",'action'=>'index'),null,true); ?>';" />
								<input type="submit" value="save" name="save" label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>
</form>
