<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_FEE')); 
	$payment_term = $this->payment_term;
?>	
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 0px; border:1px solid #ccc;font-size: 12px;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'global','controller'=>'studentscore','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center" style="font-size: 14px;"><strong><?php echo $tr->translate("ADD_NEW_STUDENT_SCORE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td  ><?php echo $tr->translate("PARENT");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" id="parent_name" name="parent_name" type="text" onChange="getSubjectName();">
									<option value="-1">select paent</option>
									<?php if(!empty($this->rows_parent)) foreach ($this->rows_parent As $rs_parent){?>
									<option value="<?php echo $rs_parent['id']?>"><?php echo $rs_parent['parent']?></option>
									<?php }?>
								</select>
							</td>
							<td  ><?php echo $tr->translate("SUBJECT");?></td>
							<td align="center">
								<input id="subject" />
							</td>
							<td  ><?php echo $tr->translate("TERM");?></td>
							<td align="center">
								<select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside"  id="term" name="term" type="text">
									<option value="1">1</option>
								</select>
							</td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("GROUP");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside"  id="group" name="group" type="text">								
										<option value="1">1</option>
										<option value="2">2</option>
								</select>
							</td>	
							<td style="white-space: nowrap;text-align: right;"><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
										<option value="1">ប្រើប្រាស់</option>
										<option value="0">មិនប្រើប្រាស់</option>
								</select>
							</td>	
													
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td colspan="2">
							</td>
						</tr>
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 	<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
									<?php $id++;if($i==0)$term = $id;
									else{$term.=','.$id;} ?>
								<?php }?>
									<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
									<input type="hidden" name="identity" id="identity"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
								 	<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<?php $frm_dept = $this->add_dept;?>

<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require('dojox.form.BusyButton');
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}

function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var faculty = '<?php echo $this->all_faculty; ?>';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
//var pay_term ="<?php //print_r($payment_term);?>";

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_ID");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_NAME");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_GRADE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STUDENT_SCORE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="4%" align="center">'+no+'</td>';
			template+='<td><input style="width:200px;" dojoType="dijit.form.TextBox" class="fullside" name="studentid_'+col+'" id="studentid_'+col+'" value="" type="text"></td>';	
			template+='<td><input style="width:200px;" dojoType="dijit.form.TextBox" class="fullside" name="studentname_'+col+'" id="studentname_'+col+'" value="" type="text"></td>';		
			template+='<td><input style="width:200px;" dojoType="dijit.form.TextBox" class="fullside" name="studentgrade_'+col+'" id="studentgrade_'+col+'" value="" type="text"></td>';
			template+='<td><input style="width:200px;" dojoType="dijit.form.NumberTextBox" class="fullside" name="studentscore_'+col+'" id="studentscore_'+col+'" value="" type="text"></td>';
			template+='<td><input style="width:200px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	 var metion = '<?php echo $this->all_metion; ?>';
	 addRow();
	 new dijit.form.FilteringSelect({
		    //store: dept_store,
		    autoComplete: true,                        
		    id: "subject",
		    name: "subject",           
		    class: 'fullside', 
		    required:'',
		    placeHolder:"Selected Subject",          
		    onChange: function() {  
		    	
		    }
		}, "subject");
	 
});


var url_get_faculty ='<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'getfaculty-option')); ?>';
function getAllFucaltyOption(f_id){                                                                      
	dojo.xhrPost({
		url: url_get_faculty,				    
		handleAs:"json", 
		load: function(response){
			//alert(response.option);
			dojo.html.set(dojo.byId("lbl_metion"+r_index),'',{
			     parseContent: true});
			faculty=response.option;
			    select='<select class="full" dojoType="dijit.form.FilteringSelect" name="metion'+r_index+'" id="metion'+r_index+'" >'+faculty+'</select>';
				dojo.html.set(dojo.byId("lbl_metion"+r_index),select, {
				     parseContent: true
				});
				dijit.byId("metion"+r_index).attr( 'value',f_id);
				alert('<?php echo $tr->translate("INSERT_SUCCESS"); ?>');
				//dijit.byId('frm_service').reset();
		},error:function(err){
			alert(err);
		}
	});
}
//get subject by parent_id
function getSubjectName(){
	parent_id=dijit.byId('parent_name').get('value');
	if(parent_id != -1){
		dijit.byId('subject').attr('value','');
		getSubject(parent_id);
	}
}
var subject_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getSubject = '<?php echo $this->url(array('module'=>'global','controller'=>'studentscore','action'=>'get-subject')); ?>';
function getSubject(parent_id){
	dojo.xhrPost({
		url:url_getSubject,
		content:{
			'parent_id':parent_id
			},
		handleAs:"json",
		load: function(data) {
			subject_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('subject').set('store',subject_store);  
		},
		error: function(err) {
			 alert(err);
		}
	});
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>