<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="width: 30cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-all-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="80%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("study_year");?></td>
	           <td> <?php echo $frm->getElement("grade_all");?></td>
			   <td> <?php echo $frm->getElement("session");?></td>
	       </tr>
		</table>
		
		<input dojoType="dijit.form.DateTextBox"   id="start_date" name="start_date" placeholder="Search....." value="<?php echo $this->search['start_date'];?>" type="text">
		<input dojoType="dijit.form.DateTextBox"   id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
</div>
	<div style="border: 1px dotted #000;background: #fff;width:29cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%; ">
								<tr>
									<td width="28%" >
										<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("ALL_STUDENT_REPORT");?></strong><br />
									</td>
									<td width="28%" align="right">
										<strong>&nbsp;</strong>
									</td>
								</tr>
								
							<style>
								table tr th{
									border: 1px solid #000;	
								}
								
							</style>
							
								<tr>
									<td colspan="3">
										<table cellpadding="4"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th rowspan="2">No.</th>
												<th rowspan="2">Student Code</th>
												<th rowspan="2">Name</th>
												<th rowspan="2">Sex</th>
												<th rowspan="2">Nationality</th>
												<th rowspan="2">Tel</th>
												<th rowspan="2">Email</th>
												<th colspan="4">Study Info</th>
											</tr>
											<tr style="font-size:10px; height: 20px;" align="center" >
												<th >AcademicYear</th>
												<th >Degree</th>
												<th >Grade</th>
												<th >Session</th>
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 23px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['stu_code'];?></th>
												<th align="left">&nbsp;<?php echo $row['name'];?>&nbsp;</th>
												<th ><?php echo $row['sex'];?></th>	
												<th ><?php echo $row['nationality'];?></th>
												<th ><?php echo $row['tel'];?></th>
												<th align="left">&nbsp;<?php echo $row['email'];?></th>
												
												
												<th ><?php echo $row['academic_year'];?></th>
												<th ><?php echo $row['degree'];?></th>
												<th align="left">&nbsp;<?php echo $row['grade'];?></th>
												<th ><?php echo $row['session'];?></th>	
												
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>
	</div>