<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_CAR')); 
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'global','controller'=>'car','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_CAR_NAME");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td><?php echo $tr->translate("Car ID")?><input type="hidden" name="id" value="<?php echo $this->rs['id'];?>"/></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Car_ID" name="Car_ID" value="<?php echo $this->rs['carid'];?>" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Car Name")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Car_Name" name="Car_Name" value="<?php echo $this->rs['carname'];?>" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Driver Name")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Driver_Name" name="Driver_Name" value="<?php echo $this->rs['drivername'];?>" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Tel")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Tel" name="Tel" value="<?php echo $this->rs['tel'];?>" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Zone")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Zone" name="Zone" value="<?php echo $this->rs['zone'];?>" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("Note")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="Note" name="Note" value="<?php echo $this->rs['note'];?>" type="text"></td>
									</tr>
									<tr>
										<td colspan="2" align="center">
											<input type="submit" value="update" name="update" label="<?php echo $tr->translate('UPDATE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>