<!DOCTYPE html>
<html>
<head>
    <title>jQuery multiselect</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />

  </head>
  <body data-spy='scroll'>
    
    <div class='container'>
      <div class='row'>
        <div class='span12'>
          <h3>Public methods</h3>
        </div>
        
        <div class='span5'>
        	<ul>
        		<li><a id="select-all" href="#">select all</a></li>
        		<li><a id="deselect-all" href="#">deselect all</a></li>
        		<li> <a id="select-100" href="#">select 100 elems</a></li>
        		<li><a id="deselect-100" href="#">deselect 100 elems</a></li>
        		<li><a id="add-option" href="#">Add option</a></li>
        		<li><a id="refresh" href="#">refresh</a></li>
        	</ul>
          <select multiple id="public-methods" name="public-methods[]">
          <option value="elem_2" disabled>elem 2</option>
          <option value="elem_3">elem 3</option>
          <option value="elem_4">elem 4</option>
          <option value="elem_5">elem 5</option>
          <option value="elem_6">elem 6</option>
          <option value="elem_7">elem 7</option>
          <option value="elem_8">elem 8</option>
          <option value="elem_9">elem 9</option>
          <option value="elem_10">elem 10</option>
          <option value="elem_11">elem 11</option>
          <option value="elem_12">elem 12</option>
          <option value="elem_13">elem 13</option>
          <option value="elem_14">elem 14</option>
          <option value="elem_15">elem 15</option>
          <option value="elem_16">elem 16</option>
          <option value="elem_86">elem 86</option>
          <option value="elem_1000">elem 1000</option></select>
          <br />
          <p>
            In this example there are
            <strong>
              1000
            </strong>
            elements
          </p>
        </div>
      </div>
    </div>
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
    
  </body>
</html>
