<center><h2>Welcome to Student Management System</h2></center>

<!DOCTYPE html>
<!-- <html> -->
<!-- <head> -->
<!--     <title>jQuery multiselect</title> -->
<!--     <meta http-equiv="content-type" content="text/html; charset=utf-8" /> -->
    <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />

<!--   </head> -->
<!--   <body data-spy='scroll'> -->
<!--     <form method="post">  -->
<!--     <div class='container'> -->
<!--       <div class='row'> -->
<!--         <div class='span12'> -->
<!--           <h3>Public methods</h3> -->
<!--         </div> -->
        
<!--         <div class='span5'> -->
<!--         	<ul> -->
<!--         		<li><a id="select-all" href="#">select all</a></li> -->
<!--         		<li><a id="deselect-all" href="#">deselect all</a></li> -->
<!--         		<li> <a id="select-100" href="#">select 100 elems</a></li> -->
<!--         		<li><a id="deselect-100" href="#">deselect 100 elems</a></li> -->
<!--         		<li><a id="add-option" href="#">Add option</a></li> -->
<!--         		<li><a id="refresh" href="#">refresh</a></li> -->
<!--         	</ul> -->
<!--           <select multiple id="public-methods" name="public-methods[]"> -->
<!--           <option value="1" disabled>elem 2</option> -->
<!--           <option value="2">elem 2</option> -->
<!--           <option value="3">elem 3</option> -->
<!--           <option value="4">elem 4</option> -->
<!--           <option value="5">elem 5</option> -->
<!--          </select> -->
<!--           <br /> -->
         
<!--         </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     	<input type="submit" value="Submit" /> -->
<!--     </form> -->
    
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
    
<!--   </body> -->
<!-- </html> -->
