<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	echo $this->headTitle('SRMS | Student Exam Fundation Year'); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'car','action'=>'rpt-car')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search by id....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
		<div id="divPrint">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;scroll;overflow-x:scroll;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							<table style="background:#fff; margin: 0 auto; border: 1px dotted #000;">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
										<strong></strong><br />
										<strong></strong><br />
									</td>
								</tr>
								<tr>
									<td><img src="" /></td>
<!-- 									<td width="20%" align="left"> -->
<!-- 										<strong>ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br /> -->
<!-- 										<strong>សាកលវិទ្យាល័យ វេស្ទើន</strong><br /><br ><br ><br > -->
<!-- 									</td> -->
									<td align="center">
										<strong>របាយការណ៏រថយន្ត</strong><br />
										<strong></strong><br />
										
										
									</td>
									<td width="20%"></td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th >ល.រ</th>
												<th >Car ID</th>
												<th >Car Name</th>
												<th>Driver Name</th>
												<th >Tel</th>
												<th >Zone</th>
												<th >Note</th>
												<th >Status</th>
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['carid'];?></th>
												<th ><?php echo $row['carname'];?></th>
												<th ><?php echo $row['drivername'];?></th>	
												<th ><?php echo $row['tel'];?></th>
												<th ><?php echo $row['zone'];?></th>
												<th ><?php echo $row['note'];?></th>
												<th ><?php echo $row['status'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
				</fieldset>		
				</td>
			</tr>
		</table>	
		</div>		
</form>