<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_SERVICE_FEE')); 
	$payment_term = $this->payment_term;
?>	
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'servicecharge','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center" style="font-size: 20px;"><strong><?php echo $tr->translate("ADD_SERVICE_FEE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td colspan="4">&nbsp;</td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("YEARS");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true"  id="from_year" name="from_year" type="text">
									<?php for($i=2014;$i<=date('Y')+1;$i++){?>
										<option value="<?php echo $i;?>"><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							<td style="white-space: nowrap;text-align: right; "><?php echo $tr->translate("TO");?></td>
							<td align="center">
								<select dojoType="dijit.form.FilteringSelect" required="true"  id="to_year" name="to_year" type="text">
									<?php for($i=2015;$i<=date('Y')+2;$i++){?>
										<option value="<?php echo $i;?>"><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							
							<td style="white-space: nowrap;text-align: right;"><?php echo $tr->translate("GENERATION");?></td>
							<td width="200px" ><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="generation" name="generation"  type="text"  required="true" ></td>
							
						</tr>
						<tr>
							
							<td  style="white-space: nowrap;"><?php echo $tr->translate("NOTE");?></td>
							<td width="200px"><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="note" name="note"  type="text"></td>
							
							<td style="white-space: nowrap;text-align: right;"><?php echo $tr->translate("CREATED_DATE");?></td>
							<td width="200px"><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="create_date" name="create_date" value="<?php echo date('Y-m-d')?>" type="text"></td>
							
							<td style="white-space: nowrap;text-align: right;"><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true"  id="status" name="status" type="text">								
										<option value="1">Active</option>
										<option value="0">Deactive</option>
								</select>
							</td>	
													
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td colspan="2">
							</td>
						</tr>
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 	<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
									<?php $id++;if($i==0)$term = $id;
									else{$term.=','.$id;} ?>
								<?php }?>
									<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
									<input type="hidden" name="identity" id="identity"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
									<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" name="save_close" dojoType="dijit.form.Button" 
								 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
									<input type="submit" label="<?php echo $tr->translate('SAVE_NEW');?>" id="save_new" name="save_new" dojoType="dijit.form.Button" 
								 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
								 	<input type="hidden" id="hidden_key" />
								 	<div id="hh"></div>
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:100%;" id="popup_dept" >
		<form style="background-color: buttonface; width:15cm;" id='frm_add_tran' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" >បន្ថែមសេវាកម្ម</legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
					
						<tr>
							<td style="width:100px"><?php echo $tr->translate("SERVICE_TYPE")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="service_type" id="service_type" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("Sport")?></option>
									    <option value="2"><?php echo $tr->translate("Life Skill")?></option>
									    <option value="3"><?php echo $tr->translate("Other")?></option>
									    <option value="4"><?php echo $tr->translate("Food")?></option>
								</select>
							</td>
						</tr>
					
						<tr>
							<td style="width:100px"><?php echo $tr->translate("ឈ្មោះសេវាកម្ម")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="service_name" id="service_name" type="text" required="required" /></td>
						</tr>
						<tr>
							<td>ពណ៌នា</td>
							<td>
								<textarea class="fullside"   style=" height: 60px !important;"
										tabindex="2" dojoType=""  id="note" name=note ></textarea>
									
							</td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("STATUS")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="status_service" id="status_service" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("Active")?></option>
									    <option value="0"><?php echo $tr->translate("Deactive")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialog();"/>
								<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addService();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>
<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}

function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var faculty = '<?php echo $this->all_faculty; ?>';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
//var pay_term ="<?php //print_r($payment_term);?>";

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
		//	temp+='<th id="lbl_titlemetion" width="50px"><?php //echo $tr->translate("MONTHLY");?></th>';
			<?php $s=0; ?>
			<?php  foreach ($payment_term as $value){?>
			
			<?php echo"temp+='<th>$value</th>';"; ?>			
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="6%" align="center">'+no+'</td>';
			template+='<td><lable id="acc_label'+col+'"><select dojoType="dijit.form.FilteringSelect" id="class_'+col+'" onchange="showpopup('+col+');" name="class_'+col+'">'+faculty+'</select></lable></td>';			
			column = 0;
			//template+='<td width="15%"> <input type="text" required="true" name="monthly'+col+'" id="monthly'+col+'" dojoType="dijit.form.NumberTextBox" style=""/><label id="subsub"></label></td>';
			for(j=0;j<payment_term;j++){ column++;
				template+='<td width="15%"><input type="text" required="true" id="fee'+col+'_'+column+'" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox" style="width: 100%;" /></td>';
			}
			template+='<td> <input type="text" required="true" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"style=""/><label id="subsub"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	 addRow();
	 
});

a=0;
function showpopup(key){
	$('#hidden_key').val(key);
	value=dijit.byId('class_'+key).get('value');
	
	//alert(value);
	if(value==-1){
		dijit.byId("popup_dept").show(key);
	}
	
}

var url_add_service = '<?php echo $this->url(array("module"=>"accounting","controller"=>"ServiceCharge","action"=>"add-service")); ?>';
function addService(){
	index = $('#hidden_key').val();
	//language = dijit.byId('language_title').get('value');
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_add_tran"),
			handleAs:"json",
			load: function(data) {
				
				getService(index,data);
		   dijit.byId('frm_add_tran').reset();
		   dijit.byId("popup_dept").hide();
				
			},
			error: function(err) {
				alert(err);
			}
	});
}
var nameContent;
var url_a = '<?php echo $this->url(array("module"=>"accounting","controller"=>"ServiceCharge","action"=>"getallfac")); ?>';
function getService(index,data){
	type = 2;
	//language = dijit.byId('language_title').get('value');
	dojo.xhrPost({
			url: url_a,
			content: {"type":type},
			handleAs:"json",
			load: function(option) {
				 dojo.html.set(dojo.byId("acc_label"+index), '<select onchange="showpopup('+index+');" name="class_'+index+'"  dojoType="dijit.form.FilteringSelect" >'
				         +option+'</select>', {
				           parseContent: true,
				           onBegin: function() {
				        	   dojo.require('dijit.form.FilteringSelect');
				           }
				       });
				 dijit.byId('frm_add_tran').reset();
				
			},
			error: function(err) {
				alert(err);
			}
	});
}


 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
}

 function getkey(key){
	 var a=key;
	 return a;
 }


	
</script>
			
			
			
			
			