<title>Course Study</title>
<?php 
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<meta charset="utf-8">
 <form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
					   <table style="width:60%">
						  <tr> 
							   <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="Search" type="text" ></td>
							  
							    <td> <input dojoType="dijit.form.DateTextBox" class="fullside" onchange="CalculateDate();" id="start_date" name="start_date" value="<?php  if(!empty($this->adv_search['start_date'])){echo $this->adv_search['start_date']; }else echo date('Y-m-01');?>"  type="text"></td>
					           <td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" value="<?php if(empty($this->adv_search['end_date'])){ echo date('Y-m-d');}else echo $this->adv_search['end_date'];?>" type="text"></td>
							  
							   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
					   </table>
 </form>
<?php 
    echo $this->list;
?>