

  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <?php 
  
  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_fee=$this->url(array('module'=>'allreport','controller'=>'fee','action'=>'rpt-fee'), null, true);
  $rpt_servicecharge=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-service-charge'), null, true);
  $rpt_collectfromco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco'), null, true);
  $rpt_tuitionfee=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-fee'), null, true);
  $rpt_studentpayment=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpayment'), null, true);
  $rpt_studentpaymentdetail=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpaymentdetail'), null, true);
  $rpt_studentlate=$this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-studentlate'), null, true);
  $rpt_expectedincome=$this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-expectedincome'), null, true);
  
  ?>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  		<li><a href="<?php echo $rpt_studentpayment;?>"><?php echo $tr->translate('Student Payment Report');?></a></li>
  		<li><a href="<?php echo $rpt_studentpaymentdetail;?>"><?php echo $tr->translate('Student Payment Detail');?></a></li>
  		<li><a href="<?php echo $rpt_servicecharge;?>"><?php echo $tr->translate('RPT_SERVICE');?></a></li>
  		<li><a href="<?php echo $rpt_tuitionfee;?>"><?php echo $tr->translate('RPT_FEE');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-studentlate'), null, true);?>"><?php echo $tr->translate('Student Payment Late Report');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-expectedincome'), null, true);?>"><?php echo $tr->translate('Expected Income Report');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'accounting','action'=>'rpt-stopservice'), null, true);?>"><?php echo $tr->translate('Student Stop Service Report');?></a></li>
  
  	</ul>
  </div>
  <div style="clear: both;"></div>