  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  
  
  $rpt_fee=$this->url(array('module'=>'allreport','controller'=>'fee','action'=>'rpt-fee'), null, true);
  $rpt_servicecharge=$this->url(array('module'=>'allreport','controller'=>'servicecharge','action'=>'rpt-service-charge'), null, true);
  $rpt_collectfromco=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-collectionco'), null, true);
  $rpt_loancollect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect'), null, true);
  
  
  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  	
  		<li><a href="<?php echo $rpt_fee;?>"><?php echo $tr->translate('RPT_FEE');?></a></li>
  		<li><a href="<?php echo $rpt_servicecharge;?>"><?php echo $tr->translate('RPT_SERVICE_CHARGE');?></a></li>
  		<li><a href="<?php echo $rpt_collectfromco;?>"><?php echo $tr->translate('RPT_SERVICE');?></a></li>
  		<li><a href="<?php echo $rpt_loancollect;?>"><?php echo $tr->translate('RPT_PROGRAM_CHARGE');?></a></li>
  
  	</ul>
  </div>
  <div style="clear: both;"></div>