<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Fee'); 
	echo $this->headTitle(''); 
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-fee')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>		
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
			<div id="divPrint">
									<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
										<tr >
											<td width="25%" align="left">
												<img style="width: 80%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td width="50%"  align="center">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​ តំលៃសិក្សា</strong><br /><br >
											</td>
											<td width="25%" align="right">
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;">No.</th>
														<th style="border: 1px solid #000;">Academic</th>
														<th style="border: 1px solid #000;">Generation</th>
														<th style="border: 1px solid #000;">Grade</th>
														<th style="border: 1px solid #000;">Time</th>
														<th style="border: 1px solid #000;">Quarter</th>
														<th style="border: 1px solid #000;">Semester</th>
														<th style="border: 1px solid #000;">Year</th>
														<th style="border: 1px solid #000;">Note</th>
													</tr>
												<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;"><?php echo $i;?></th>
														<th style="border: 1px solid #000;"><?php echo $row['academic'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['generation'];?></th>
														<th align="left" style="border: 1px solid #000;">&nbsp;&nbsp;<?php echo $row['class'];?></th>	
														<th style="border: 1px solid #000;"><?php echo $row['time'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['quarter'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['semester'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['year'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['remark'];?></th>
													</tr>
												<?php }?>	
												</table>	
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr >
											<td align="center" width="25%">
												<span style="font-weight: bold;font-size: 14px;">Verified by</span>
											</td>
											<td  width="50%">
												&nbsp;
											</td>
											<td align="center"  width="25%">
												<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
											</td>
										</tr>
									</table>
			</div>		
</div>










