<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Suspend Service'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by student name....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px;">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
									<td>&nbsp;</td>
							</tr>
								<tr>
								<td width="20%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><u>ពត៌មាន សិស្សដែលផ្អាកសេវាកម្ម</u></strong><br >
								</td>
								<td align="right" width="20%">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  }
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
												<style> td{padding:0 3px; }</style>
										  <?php
											$student_id =0;
										 	 $i=0; $total=0;if (!empty($this->rs)) foreach($this->rs as $rs){ $i++;
										 	 if($rs['stu_id']!=$student_id){
										  ?>
										  <tr style="border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff;"><td colspan="8">&nbsp;</td></tr>
										  <tr style="font-size:10px; height: 23px; border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff; "​>
										  	<td align="left" colspan="8">
										  		<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 10px;font-family:'Khmer MEF2';"><?php echo 'Student ID :'.$rs['stu_code'] .'  Student Name :'.$rs['kh_name'].' / '.$rs['en_name'].'  Gender : '.$rs['sex'].'  Academic Year : '.$rs['academic'];?></strong><br />
										  	</td>
										  </tr>
										   <tr style="font-size:10px; height: 20px;" align="center">
										    <th>&nbsp;N.o&nbsp;</th>
										    <th>&nbsp;Reciept N.o&nbsp;</th>
										    <th>&nbsp;Service Name&nbsp;</th>
											<th>&nbsp;Payment Term&nbsp;</th>
											<th>&nbsp;Type Suspend&nbsp;</th>
											<th>&nbsp;Reason&nbsp;</th>
											<th>&nbsp;Note&nbsp;</th>
											<th>&nbsp;Date&nbsp;</th>
										  </tr>
										 <?php  }
										 $student_id=$rs['stu_id'];
										 ?>
										   <tr style="font-size:10px; height: 18px; border-bottom: 1px solid #000;"​ align="center">
										  	<td><?php echo $i;?></td>
										   	<td><?php echo $rs['suspend_no']; ?></td>
										   	<td><?php echo $rs['service']; ?></td>
										  	<td><?php echo $rs['payment_term']; ?></td>
										  	<td><?php echo $rs['type_suspend']; ?></td>
										   	<td><?php echo $rs['reason']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										   	<td><?php echo $rs['define_date']; ?></td>
										  </tr>
										  <?php } ?>
										</table>
									
									</td>
								</tr>
							</table>
	</div>	
</div>

