<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Payment'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px; ">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black; color:#000; font-size: 13px; font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black; color:#000; font-size: 13px; font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
									<td>&nbsp;</td>
							</tr>
							<tr>
								<td width="25%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style=" font:bold 13px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
								</td>
								<td align="right" width="25%">
								</td>
							</tr>
							<tr>
								<td width="30%" align="left">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student Name  : <?php echo $this->rr['en_name']?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Sex  : <?php echo $this->rr['sex']?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student ID  : <?php echo $this->rr['stu_code']?></strong><br />
								</td>
								<td></td>
								<td width="25%" align="left" style=" padding-right: 20px;">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Reciept N.o : <?php echo $this->rr['receipt_number']?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Date Paid : <?php echo date('d-m-Y',strtotime($this->rr['create_date']));?></strong><br />
									
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										  <tr style="font-size:10px; height: 30px; align="center" >
										    <th rowspan="2">&nbsp;N.o&nbsp;</th>
											<th rowspan="2">&nbsp;Type Service&nbsp;</th>
											<th rowspan="2">&nbsp;Payment Term&nbsp;</th>
											<th rowspan="2">&nbsp;Price&nbsp;</th>
											<th rowspan="2">&nbsp;Amount&nbsp;</th>
											<th rowspan="2">&nbsp;Discount&nbsp;</th>
											<th rowspan="2">&nbsp;Sub Total&nbsp;</th>
										  </tr>
										  <tr></tr>
											<style> td{padding:0 3px; }</style>
										  <?php $i=0; if(!empty($this->row)) foreach($this->row as $rs){ $i++;?>
										  <tr style="font-size:10px;height: 23px;"​ align="center">
										    <td><?php echo $i;?></td>
										    <td><?php echo $rs['service'];?></td>
										    <td><?php echo $rs['payment_term'];?></td>
										     <td>$ <?php echo $rs['price'];?></td>
										    <td><?php echo $rs['amount']; ?></td>
										    <td><?php echo $rs['discount_percent'];?>%</td>
										    <td><?php echo $rs['total_payment'];?>$</td>
										  </tr>
										  <?php } ?>
										  <tr style="font-size:10px;height: 23px;"​ align="center">
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;"" colspan="5"></td>
										  	<td>Total Amount</td>
										  	<td>$ <?php echo $this->rr['total_payment']?></td>
										  </tr>
										  <tr style=" font-size:10px;height: 23px;"​ align="center">
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;" colspan="5"></td>
										  	<td>Paid Amount</td>
										  	<td>$ <?php echo $this->rr['paid_amount']?></td>
										  </tr>
										   <tr style="font-size:10px;height: 23px;"​ align="center">
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;"" colspan="5"></td>
										  	<td>Balance Due</td>
										  	<td>$ <?php echo $this->rr['balance_due']?></td>
										  </tr>
										</table>
									
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">អ្នកទទួល   <?php echo $this->rr['USER'];?></strong><br />
									</td>
								</tr>
									<tr>
									<td></td>
									<td></td>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ហត្ថលេខា </strong><br />
									</td>
								</tr>
							</table>
	</div>	
</div>

