<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Payment'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<form id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-paymentdetailbytype')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table width="100%" style="margin: 0 auto; background: #fff;">
			<tr>
				<td>
					<input class="fullside" dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Advance search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
				</td>
				<td>
					<input class="fullside" name="from_date" id="from_date" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->search['start_date'];?>" type="text">
				</td>
				<td>
					<input class="fullside" name="to_date" id="to_date" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->search['end_date'];?>" type="text">
				</td>
				<td align="left" colspan="2">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</td>
			<tr>
				<td>
					<select class="fullside" name="service" id="service" dojoType="dijit.form.FilteringSelect">
							<option value="-1" >- - -Search by service type- - -</option>
							<?php if(!empty($this->service)) foreach ($this->service as $row){?>
							<option value='<?php echo $row['service_id'];?>' <?php if($row['service_id']== $this->search['service_type']) echo "selected='Selected'"?>><?php echo $row['title'];?></option>
							<?php }?>
					</select>
				</td>
				<td colspan="4" ></td>
			</tr>
		</table>
</form>

<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px; ">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">សាលារៀន អាស៊ាន ហ៊ែរីថេដ</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ASEAN HERITAGE SCHOOL</strong><br />
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
							</tr>
							<tr>
								<td colspan="3"  align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><u>របាយការណ៏ប្រាក់ចំណូលពី ការបង់ប្រាក់របស់សិស្ស</u></strong><br >
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										 
										  <tr></tr>
												<style> td{padding:0 3px; }</style>
										<?php $total_dic=0; 
												$grand_total =0;  
												$service_id=0;
												$i=0; 
												$total=0; $total_amount=0; $total_admin_nOhter = 0;
												$total_fee=0;
											 ?>
										<?php if(empty($this->row)){}?> 
										  <?php  if(!empty($this->row)) foreach($this->row as $key => $rs){ $i++;?>
										  <?php  
											  if($rs['service_id']!=$service_id){	?>
											   <?php  if($key>0 ){?>
													 <tr style="font-size:10px; color:#000; height: 18px;"​ align="center">
													 			<td style="border-left: solid 1px #fff; border-bottom: 1px #fff solid;" colspan="14"></td>
													 			<th style=" border-bottom: 1px #000 solid; background-color: #ccc; width: 38%; font-weight:bold; font-size: 10px;">&nbsp;Total&nbsp;</th>
																<td style=" border-bottom: 1px #000 solid; color:#F00; font-weight:bold; font-size: 10px;">$ <?php echo number_format($total,2);?></td>
													 </tr>
													 </table>
													<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
												<?php }?>
										
											  <tr style="font-size:10px; color:#000; height: 23px; border-left:1px solid #fff; border-right:1px solid #fff; border-top: 1px solid #fff;"​ align="center">
											    <td colspan="16" style="text-align:left">
											    	<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';" ><?php echo 'Service Name :'.$rs['service']; ?></strong>
											    </td>
											  </tr>
											   <tr style="font-size:10px; height: 22px; align="center" >
											    <th>&nbsp;N.o&nbsp;</th>
											    <th>&nbsp;Reciept N.o&nbsp;</th>
												<th>&nbsp;Khmer Name&nbsp;</th>
												<th>&nbsp;English Name&nbsp;</th>
												<th>&nbsp;Payment Term&nbsp;</th>
												<th>&nbsp;Fee&nbsp;</th>
												<th>&nbsp;Qty&nbsp;</th>
												<th>&nbsp;Discount&nbsp;</th>
												<th>&nbsp;Admin Fee&nbsp;</th>
												<th>&nbsp;Other Fee&nbsp;</th>
												<th>&nbsp;Amount&nbsp;</th>
												<th>&nbsp;Sub Total&nbsp;</th>
												<th>&nbsp;Amount In Khmer&nbsp;</th>
												<th>&nbsp;Date Paid&nbsp;</th>
												<th>&nbsp;User&nbsp;</th>
												<th>&nbsp;Remark&nbsp;</th>
											  </tr>
											   <?php $total=0;
											 }
										   
										 	$service_id=$rs['service_id'];
										 	$fee_dic = (($rs['fee']* $rs['qty']) * $rs['discount_percent'])/100;
										 	$after_dic= ($rs['fee']* $rs['qty']) - $fee_dic;
										 	$subtotal= $after_dic + $rs['admin_fee']+ $rs['other_fee'];
										 	$total = $subtotal + $total;
										 	 ?>
										   <tr style="font-size:10px; color:#000; height: 18px; border-bottom: 1px solid #000;"​ align="center">
										  	<td><?php echo $i;?></td>
										    <td style="color: #F00;"><?php echo $rs['receipt_number']; ?></td>
										    <td style=" white-space:nowrap; text-align:left"><?php echo $rs['kh_name']; ?></td>
										    <td style=" white-space:nowrap; text-align:left"><?php echo $rs['en_name']; ?></td>
										    <td style="text-align:left"><?php echo $rs['payment_term']; ?></td>
										    <td>$ <?php echo number_format($rs['fee'],2); if(empty($rs['fee']))echo '0.00'; ?></td>
										    <td><?php echo $rs['qty']; if(empty($rs['qty']))echo '00'; ?></td>
										    <td><?php echo $rs['discount_percent']; if(empty($rs['discount_percent']))echo '0'; ?>%</td>
										    <td>$ <?php echo number_format($rs['admin_fee'],2); if(empty($rs['admin_fee']))echo '0.00'; ?></td>
										    <td>$ <?php echo number_format($rs['other_fee'],2); if(empty($rs['other_fee']))echo '0.00'; ?></td>
										    <td>$ <?php echo number_format($rs['amount'],2); if(empty($rs['amount']))echo '0.00'; ?></td>
										    <td>$ <?php echo number_format($subtotal,2); ?></td>
										    <td><?php echo $rs['amount_in_khmer']; ?></td>
										    <td><?php echo date('d-m-Y', strtotime($rs['create_date']));?></td>
										    <td><?php echo $rs['user']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										  </tr>
										  <?php $grand_total = $grand_total+ $subtotal;
										  	$total_dic = $total_dic + $fee_dic;
										  	$total_fee = $total_fee + $rs['fee'];
										  	$total_amount = $total_amount + $rs['amount'];
										  	$total_admin_nOhter = $total_admin_nOhter + $rs['other_fee']+$rs['admin_fee'];
										  ?>
										  <?php } ?>
										  <?php if (empty($total)){}?>
										   <?php if(!empty($total)){?>
										  <tr style="font-size:10px; color:#000; height: 18px;"​ align="center">
												<td style="border-left: solid 1px #fff; border-bottom: 1px #fff solid;" colspan="14"></td>
												<th style=" border-bottom: 1px #000 solid; background-color: #ccc; width: 38%; font-size: 10px;">&nbsp;Total&nbsp;</th>
												<td style=" border-bottom: 1px #000 solid; color:#F00; font-weight:bold; font-size: 10px;">$ <?php echo number_format($total,2);?></td>
										 </tr>
										 <?php }?>
									</table>
								</td>
							</tr>
							<tr><td colspan="3">&nbsp;</td></tr>
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>
							<?php if (empty($total_fee)){}?>
							<?php if (!empty($total_fee)){?>
							<tr>
								<td colspan="2"></td>
								<td>
									<table border="1" align="right" style="  width:50%; margin-right:0.5%; white-space:nowrap;">
										<tr style="font-size:10px; background:#ccc; height: 20px; align="center">
											<th>&nbsp;Total Fee&nbsp;</th>
											<th>&nbsp;Total Discount&nbsp;</th>
											<th>&nbsp;Total Amount&nbsp;</th>
											<th>&nbsp;Total Admin & Other Fee&nbsp;</th>
											<th>&nbsp;Grand Total&nbsp;</th>
										</tr>
										<tr align="center" style=" height:18px; font-size:10px; padding: 1px;" >
											<td>$ <?php echo number_format($total_fee,2);?></td>
											<td>$ <?php echo number_format($total_dic,2);?></td>
											<td>$ <?php echo number_format($total_amount,2); if(empty($rs['amount']))echo '0.00'; ?></td>
											<td>$ <?php echo number_format($total_admin_nOhter,2)?></td>
											<td style=" font-weight:bold; font-size: 10px; color:#F00;">$ <?php echo number_format($grand_total,2)?></td>
										</tr>
									  </table>
								</td>
							</tr>
							<?php }?>
					</table>
	</div>	
</div>

