<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Payment'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpaymentdetail')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by student name....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>

<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px; ">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
									<td>&nbsp;</td>
							</tr>
							<tr>
								<td width="20%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><u>របាយការណ៏លំអិតប្រាក់ចំណូលរបស់និស្សិត</u></strong><br >
								</td>
								<td align="right" width="20%">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										  <tr style="font-size:10px; height: 30px; align="center" >
										    <th rowspan="2">N.o</th>
										    <th rowspan="2">Reciept N.o</th>
											<th rowspan="2">Khmer Name</th>
											<th rowspan="2">English Name</th>
											<th rowspan="2">Service Type</th>
											<th rowspan="2">Payment Term</th>
											<th rowspan="2">Amount</th>
											<th rowspan="2">Discount</th>
											<th rowspan="2">Total Payment</th>
											<th rowspan="2">Paid Amount</th>
											<th rowspan="2">Balance Due</th>
											<th rowspan="2">Return Amount</th>
											<th rowspan="2">Amount In Khmer</th>
											<th rowspan="2">Date Paid</th>
											<th rowspan="2">User</th>
											<th rowspan="2">Remark</th>
										  </tr>
										  <tr></tr>
												<style> td{padding:0 3px; }</style>
										  <?php $i=0; foreach($this->row as $rs){ $i++;?>
										  <tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										    <td><?php echo $i;?></td>
										    <td><?php echo $rs['receipt_number']; ?></td>
										    <td style=" white-space:nowrap; text-align:left"><?php echo $rs['kh_name']; ?></td>
										    <td style=" white-space:nowrap; text-align:left"><?php echo $rs['en_name']; ?></td>
										    <td><?php echo $rs['service']; ?></td>
										    <td><?php echo $rs['payment_term']; ?></td>
										     <td><?php echo $rs['amount']; ?></td>
										    <td><?php echo $rs['discount_percent']; ?>%</td>
										    <td>$ <?php echo $rs['total_payment']; ?></td>
										    <td>$ <?php echo $rs['paid_amount']; ?></td>
										    <td>$ <?php echo $rs['balance_due']; ?></td>
										    <td><?php echo $rs['return_amount']; ?></td>
										    <td><?php echo $rs['amount_in_khmer']; ?></td>
										    <td><?php echo date('d-m-Y', strtotime($rs['create_date']));?></td>
										    <td><?php echo $rs['user']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										  </tr>
										  <?php } ?>
										</table>
									
									</td>
								</tr>
							</table>
	</div>	
</div>

