<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Car'); 
	echo $this->headTitle(''); 
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-car')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<select dojoType="dijit.form.FilteringSelect"   id="searchby" name="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Car ID</option>
			<option value="2">Car Name</option>
			<option value="3">Driver Name</option>
		</select>
		<input dojoType="dijit.form.TextBox" placeholder="ស្វែងរក..." id="txtsearch" name="txtsearch" value="" type="text">	
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>	
<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">	
		<div id="divPrint">
		
					<table  style="background:#fff; margin: 0 auto;text-align: center;padding: 1cm;">
						<tr style="font-size: 13px;">
							<td colspan="2"></td>
								<td align="right">
									<strong></strong><br />
									<strong></strong><br />
								</td>
						</tr>
						<tr>
							
							<td width="25%" align="left">
								<img style="width: 70%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
							</td>
							<td align="center">
								<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏រថយន្ត</strong><br /><br />
								<strong></strong>
							</td>
							<td width="28%" align="right">
								<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
								<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
							</td>
						</tr>
						<tr>
							<td colspan="3">
								<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse; border: 1px solid #000;"  border="1" >
									<tr style="font-size:11px; height: 20px;" align="center" >
										<th >ល.រ</th>
										<th >Car ID</th>
										<th >Car Name</th>
										<th>Driver Name</th>
										<th >Tel</th>
										<th >Zone</th>
										<th >Note</th>
									</tr>
								<?php $i=0; if(!empty($this->rs)) foreach ($this->rs AS $row) { $i++;?>
									<tr style="font-size:11px; height: 20px;" align="center" >
										<th ><?php echo $i;?></th>
										<th ><?php echo $row['carid'];?></th>
										<th align="left">&nbsp;<?php echo $row['carname'];?></th>
										<th align="left">&nbsp;<?php echo $row['drivername'];?></th>	
										<th ><?php echo $row['tel'];?></th>
										<th ><?php echo $row['zone'];?></th>
										<th align="left">&nbsp;<?php echo $row['note'];?></th>
									</tr>
								<?php }?>	
							</table>	
						</td>
					</tr>
				</table>
				
		</div>		
</div>