<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Payment'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr>
								<td width="25%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="left">
									<strong style=" font:bold 13px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
								</td>
								<td align="right" width="25%">
								</td>
							</tr>
							<tr>
								<td width="40%" align="left">
									<strong style=" line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student Name  : <?php echo $this->rr['en_name'].' / ';echo $this->rr['kh_name']?></strong><br />
									<strong style=" line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Sex  : <?php echo $this->rr['sex']?></strong><br />
									<strong style=" line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student ID  : <?php echo $this->rr['stu_code']?></strong><br />
								</td>
								<td></td>
								<td width="25%" align="left" style=" padding-right: 20px;">
									<strong style="line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Reciept N.o : <?php echo $this->rr['receipt_number'];?></strong><br />
									<strong style="line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Date Paid : <?php echo date('d-m-Y',strtotime($this->rr['create_date']));?></strong><br />
									<strong style="line-height:18px; font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"></strong><br />
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap; padding: 0px; margin: 0px;">
										  <tr style="font-size:10px; height: 20px;" align="center" >
										    <th>&nbsp;N.o&nbsp;</th>
											<th>&nbsp;Type Service&nbsp;</th>
											<th>&nbsp;Payment Term&nbsp;</th>
											<th>&nbsp;Fee&nbsp;</th>
											<th>&nbsp;Qty&nbsp;</th>
											<th>&nbsp;Discount&nbsp;</th>
											<th>&nbsp;Amount&nbsp;</th>
											<th>&nbsp;Sub Total&nbsp;</th>
										  </tr>
										  <tr></tr>
											<style> td{padding:0 3px; }</style>
										  <?php $i=0; $total=0; if(!empty($this->row)) foreach($this->row as $rs){ $i++;?>
										  <tr style="font-size:10px;height: 15px;"​ align="center">
										  <?php $subtotal = $rs['fee']-(($rs['fee']*$rs['discount_percent'])/100); ?>
										    <td><?php echo $i;?></td>
										    <td><?php echo $rs['service'];?></td>
										    <td><?php echo $rs['payment_term']; ?></td>
										    <td>$ <?php echo $rs['fee']; if(empty($rs['fee'])) echo '0.00';?></td>
										    <td><?php echo $rs['qty']; if(empty($rs['qty'])) echo '00';?></td>
										    <td><?php echo $rs['discount_percent']; if(empty($rs['discount_percent'])) echo '0';?>%</td>
										    <td>$ <?php echo $rs['amount']; ?></td>
										    <td>$ <?php echo $subtotal; if(empty($rs['subtotal'])) echo '0.00';?></td>
										  </tr> <?php $total = $total + $subtotal; ?>
										  <?php } ?>
										  <tr style="font-size:10px;height: 15px;"​>
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;" colspan="6"></td>
										  	<td>Total Amount</td>
										  	<td>$ <?php echo $total.'.00';//echo $this->rr['total_payment']; if(empty($this->rr['total_payment'])) echo '0.00';?></td>
										  </tr>
										  <tr style=" font-size:10px;height: 15px;"​>
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;" colspan="6"></td>
										  	<td>Paid Amount</td>
										  	<td>$ <?php echo $this->rr['paid_amount']; if(empty($this->rr['paid_amount'])) echo '0.00';?></td>
										  </tr>
										   <tr style="font-size:10px;height: 15px;"​>
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;" colspan="6"></td>
										  	<td>Balance Due</td>
										  	<td>$ <?php echo $this->rr['balance_due']; if(empty($this->rr['balance_due'])) echo '0.00';?></td>
										  </tr>
										   <tr style="font-size:10px; height: 15px; "​>
										  	<td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff;" colspan="6"></td>
										  	<td>Return Amount</td>
										  	<td>$ <?php echo $this->rr['return_amount']; if(empty($this->rr['return_amount'])) echo '0.00';?></td>
										  </tr>
										</table>
									
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">អ្នកទទួល   <?php echo $this->rr['USER'];?></strong><br />
									</td>
								</tr>
									<tr>
									<td></td>
									<td></td>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ហត្ថលេខាអ្នកទទួល </strong><br />
									</td>
								</tr>
							</table>
	</div>	
</div>

