<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Balance'); 
	echo $this->headTitle(''); 
	
?>	
<div style="width: 27cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentbalance')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search....." value="" type="text">
			</td>
			<td>
				<input class="fullside" name="from_date" id="from_date" dojoType="dijit.form.DateTextBox" placeholder="from date" value="<?php echo $this->search['start_date'];?>" type="text">
			</td>
			<td>
				<input class="fullside" name="to_date" id="to_date" dojoType="dijit.form.DateTextBox" placeholder="to date" value="<?php echo $this->search['end_date'];?>" type="text">
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;">
	<div id="divPrint">
									<table  style="background:#fff; margin: 0 auto; padding: 0.5cm;">
										<tr>
											<td width="28%" align="left">
												<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td align="center" width="44%">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សជំពាក់ថ្លៃសេវាកម្ម</strong><br /><br >
											</td>
											<td width="28%" align="right">
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;">&nbsp;N.o&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Receipt No&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Academic Year&nbsp;</th>
														<th style="border: 1px solid #000;">Code</th>
														<th style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Sex&nbsp;</th>
														<th style="border: 1px solid #000;">Service Name</th>
														<th style="border: 1px solid #000;">Total</th>
														<th style="border: 1px solid #000;">&nbsp;Discount&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Total Payment&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Paid Amount&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Balance&nbsp;</th>
														<th style="border: 1px solid #000;">Paid Date</th>
														<th style="border: 1px solid #000;">Validate</th>
														<th style="border: 1px solid #000;">Note</th>
													</tr>
												<?php $i=0;$totalpaid=0;$totalbalance=0; foreach ($this->rs AS $row) { $i++;?>
													<tr style="font-size:10px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;"><?php echo $i;?></th>
														<th style="border: 1px solid #000;"><?php echo $row['receipt'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['year'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></th>	
														<th style="border: 1px solid #000;"><?php echo $row['sex'];?></th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['fee'];?>&nbsp;</th>
														<th style="border: 1px solid #000;"><?php echo $row['discount'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['payment'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['paid'];?></th>
														<?php if($row['complete']==0){ ?>
															<th style="border: 1px solid #000;color:red;"><?php echo $row['balance'];?></th>
															<?php $totalbalance=$totalbalance + $row['balance'];?>
														<?php }else{?>
															<th style="border: 1px solid #000;"><?php echo $row['balance'];?></th>
															<?php $totalpaid=$totalpaid+$row['balance'];?>
														<?php }?>
														<th style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['paid_date']));?>&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['validate']));?>&nbsp;</th>
														<?php if($row['complete']!=0){ ?>
															<th style="border: 1px solid #000;">&nbsp;<?php echo $row['comment'];?>&nbsp;</th>
														<?php }else{?>
															<th style="border: 1px solid #000;color:red;">&nbsp;<?php echo $row['comment'];?>&nbsp;</th>
														<?php }?>
													</tr>
												<?php }?>	
												</table>	
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<?php //if (empty($total_fee)){}?>
										<?php ///if (!empty($total_fee)){?>
										<tr>
											<td colspan="2"></td>
											<td>
												<table border="1" align="right" style="width:50%; margin-right:0.5%; white-space:nowrap;border-collapse: collapse;border: 1px #000 solid;">
													<tr style="font-size:10px; background:#ccc; height: 20px;width: 400px;" align="center">
														<th>&nbsp;Total Balance Paid &nbsp;</th>
														<th>&nbsp;Total Balance Remain&nbsp;</th>
													</tr>
													<tr align="center" style=" height:18px; font-size:10px; padding: 1px;font-weight: bold;" >
														<td>$ <?php echo number_format($totalpaid,2);?></td>
														<td style="color: red;">$ <?php echo number_format($totalbalance,2);?></td>
													</tr>
												  </table>
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr style="">
											<td colspan="3">
												<span style="padding-left: 85px;font-weight: bold;font-size: 14px;">Verified by</span>
												<span style="padding-left: 610px;font-weight: bold;font-size: 14px;">Prepared by</span>
											</td>
<!-- 											<td > -->
<!-- 												<span>Prepare by CamApp Technology</span> -->
<!-- 											</td> -->
										</tr>
										
										<?php //}?>
									</table>
							
			</div>		
</div>





