<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Payment Late'); 
	echo $this->headTitle(''); 
	
?>	
<?php
// 			$date1=date_create("2013-03-15");
// 			$date2=date_create("2013-04-15");
// 			$diff=date_diff($date1,$date2);
// 			echo $diff->format("%R%a days");exit();
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentpaymentlate')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<input class="fullside" name="from_date" id="from_date" dojoType="dijit.form.DateTextBox" placeholder="from date" value="<?php echo $this->search['start_date'];?>" type="text">
			</td>
			<td>
				<input class="fullside" name="to_date" id="to_date" dojoType="dijit.form.DateTextBox" placeholder="to date" value="<?php echo $this->search['end_date'];?>" type="text">
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
									<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
										
										<tr>
											<td width="28%" align="left">
												<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td align="center" width="44%">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សបង់យឺត</strong><br />
												<span style="font-weight: bold;font-size: 11px;">From &nbsp;<?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;To&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));?></span><br /><br />
											</td>
											<td width="28%" align="right">
												
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;">&nbsp;N.o&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Receipt No&nbsp;</th>
														<th style="border: 1px solid #000;">Code</th>
														<th style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Sex&nbsp;</th>
														<th style="border: 1px solid #000;">Service Name</th>
														<th style="border: 1px solid #000;">Paid Date</th>
														<th style="border: 1px solid #000;">Validate</th>
														<th style="border: 1px solid #000;">Late (Days)</th>
														
													</tr>
												<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
												
													$date1=date_create($row['end']);
													$date2=date_create(date('Y-m-d'));
													$diff=date_diff($date1,$date2);
													$day=$diff->format("%R%a");
// 													echo $diff->format('%R'); // use for point out relation: smaller/greater
// 													echo $diff->days;
												?>
													<tr style="font-size:10px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;"><?php echo $i;?></th>
														<th style="border: 1px solid #000;"><?php echo $row['receipt'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></th>	
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</th>
														<th style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</th>
														<th align="center" style="border: 1px solid #000;color: red;">&nbsp;<?php echo abs($day);?> days</th>
 													</tr>
												<?php }}?>	 
												</table>	
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr >
											<td align="center" width="25%">
												<span style="font-weight: bold;font-size: 14px;">Verified by</span>
											</td>
											<td  width="50%">
												&nbsp;
											</td>
											<td align="center"  width="25%">
												<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
											</td>
										</tr>
										
									</table>
							
			</div>		
</div>





