	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$global=$acl=$this->url(array('module'=>'allreport','controller'=>'index','action'=>'index'), null, true);
	$registrar=$acl=$this->url(array('module'=>'allreport','controller'=>'receiptionist','action'=>'index'), null, true);
	$accoutning=$acl=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	$fundation=$acl=$this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'index'), null, true);
	
	/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		$arr_param_menu=array( 
			'home'=>array(
						
			),
			'registrar'=>array(
			    'index'=>'<li><a href="">'.$tr->translate("RECEIPT").'</a></li>',
// 			    'register'=>'<li><a href="">'.$tr->translate("Receipt").'</a></li>',
			    'register'=>'<li><a href="">'.$tr->translate("INVOICE").'</a></li>',
				'coursestudy'=>'<li><a href="">'.$tr->translate("INVOICE").'</a></li>',
				'request'=>'<li><a href="">'.$tr->translate("STUDENT_REQUEST").'</a></li>',		 					
				'gepregister'=>'<li><a href="">'.$tr->translate("ចុះឈ្មោះបង់លុយ(TC)").'</a></li>',
				'calculator'=>'<li><a href="">'.$tr->translate("តារាងគណនាចំនួនទឹកប្រាក់").'</a></li>',
				'global'=>'<li><a href="">'.$tr->translate("របាយការណ៏ទាំងអស់").'</a></li>',
				
			),
			'foundation'=>array(
				'studentgroup'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
				'studentchangegroup'=>'<li><a href="">'.$tr->translate("STUDENT_CHANGE_GROUP").'</a></li>',
				'studentdrop'=>'<li><a href="">'.$tr->translate("STUDENT_DROP").'</a></li>',
				'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
				'studentstudy'=>'<li><a href="">'.$tr->translate("STUDENT_STUDY").'</a></li>',
					
				'register'=>'<li><a href="">'.$tr->translate("Register").'</a></li>',
				'kindergarten'=>'<li><a href="">'.$tr->translate("Kindergarten Register").'</a></li>',
		        'student'=>'<li><a href="">'.$tr->translate("តារាងនិសិ្សត").'</a></li>',
				'attendent'=>'<li><a href="">'.$tr->translate("អវត្តមាននិសិ្សត").'</a></li>',
		        'score'=>'<li><a href="">'.$tr->translate("តារាងពិន្ទុ").'</a></li>',
			    'result'=>'<li><a href="">'.$tr->translate("និស្សិតទទួលសញ្ញាបត្រ").'</a></li>',
				'language'=>'<li><a href="">'.$tr->translate("Add Degree Language").'</a></li>',
				'studentgroup'=>'<li><a href="">'.$tr->translate("Student Group").'</a></li>',
				'studentstudy'=>'<li><a href="">'.$tr->translate("Student Study").'</a></li>',
			    'certificate'=>'<li><a href="">'.$tr->translate("របាយការណ៏ទាំងអស់").'</a></li>',

			//	'register'=>'<li><a href="">'.$tr->translate("REGISTER").'</a></li>',
				'kindergarten'=>'<li><a href="">'.$tr->translate("KINDERGARTEN_REGISTER").'</a></li>',
		        'student'=>'<li><a href="">'.$tr->translate("STUDENT_LIST").'</a></li>',
// 				'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
		        'score'=>'<li><a href="">'.$tr->translate("SCORE_LIST").'</a></li>',
			    'result'=>'<li><a href="">'.$tr->translate("STUDENT_CERTIFICATION").'</a></li>',
			    'certificate'=>'<li><a href="">'.$tr->translate("ALL_REPORT").'</a></li>',
			),
			'accounting'=>array(				
				'fee'=>'<li><a href="">'.$tr->translate("TUITION_FEE").'</a></li>',
				'Servicecharge'=>'<li><a href="">'.$tr->translate("SERVICE_FEE").'</a></li>',
				'service'=>'<li><a href="">'.$tr->translate("SERVICE_NAME").'</a></li>',
				'services'=>'<li><a href="">'.$tr->translate("SERVICE_CATE").'</a></li>',
				'Servicear'=>'<li><a href="">'.$tr->translate("SERVICE_INCOME").'</a></li>',
				'service'=>'<li><a href="">'.$tr->translate("Services").'</a></li>',
				'services'=>'<li><a href="">'.$tr->translate("SERVICE_PROGRAMER_CATE").'</a></li>',
				/*'Servicear'=>'<li><a href="">'.$tr->translate("ចំនូលពីសេវាកម្ម").'</a></li>',
				'StudentDebt'=>'<li><a href="">'.$tr->translate("តារាងជំពាក់ជំពាក់").'</a></li>',
				'StudentLate'=>'<li><a href="">'.$tr->translate("STUDENT_LATE").'</a></li>',
				'Programcharge'=>'<li><a href="">'.$tr->translate("GEPPROGRAM_FEE").'</a></li>',
				'program'=>'<li><a href="">'.$tr->translate("SUBJECT").'</a></li>'
				'program'=>'<li><a href="">'.$tr->translate("Subjects").'</a></li>',*/
				'exchangerate'=>'<li><a href="">'.$tr->translate("ពត៌មានការប្ដូរប្រាក់").'</a></li>',
			),
			'global'=>array(
					'group'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
					'academicyear'=>'<li><a href="">'.$tr->translate("ACADEMIC_YEAR").'</a></li>',
					'lecturer'=>'<li><a href="">'.$tr->translate("LACTURER").'</a></li>',
					'subject'=>'<li><a href="">'.$tr->translate("SUBJECT").'</a></li>',
					'faculty'=>'<li><a href="">'.$tr->translate("DEGREE").'</a></li>',
					'major'=>'<li><a href="">'.$tr->translate("CLASS").'</a></li>',
					'car'=>'<li><a href="">'.$tr->translate("CAR").'</a></li>',
					'Occupation'=>'<li><a href="">'.$tr->translate("OCCUPATION").'</a></li>',
					'province'=>'<li><a href="">'.$tr->translate("CITY_PROVINCE").'</a></li>',
					'scholarship'=>'<li><a href="">'.$tr->translate("SCHOLARSHIP").'</a></li>',
// 					'Scholarship'=>'<li><a href="">'.$tr->translate("SCHOLARSHIP").'</a></li>',
					'room'=>'<li><a href="">'.$tr->translate("ROOM_NAME").'</a></li>',
					'situation'=>'<li><a href="">'.$tr->translate("SITUATIONS").'</a></li>',
					'highschool'=>'<li><a href="">'.$tr->translate("HIGHSCHOOL").'</a></li>',
					'icon'=>'<li><a href="">'.$tr->translate("ICON").'</a></li>',
			),
			'user'=>array(
				'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
			),	
			'rsvAcl'=>array(
					 	'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
					    'acl'=>'<li><a href="">'.$tr->translate("ACL").'</a></li>',
						'user'=>'<li><a href="">'.$tr->translate('USER').'</a></li>',
						'userAccess'=>'<li><a href="">'.$tr->translate("USER_ACCESS").'</a></li>',
						'userType'=>'<li><a href="">'.$tr->translate("USER_TYPE").'</a></li>',
				),
			'backup'=>array(
						'index'=>'<li><a href="">'.$tr->translate("Backup List").'</a></li>',
				),
			'allreport'=>array(
				'global'=>"<li><span class''><a href=".$global.">".$tr->translate("របាយការណ៏ ផ្សេងៗ")."</a></span></li>",
				'registra'=>"<li><span class''><a href=".$registrar.">".$tr->translate("របាយការណ៏ ការិយាល័យចុះឈ្មោះ")."</a></span></li>",
				'fundation'=>"<li><span class''><a href=".$fundation.">".$tr->translate("របាយការណ៏ រដ្ឋបាល")."</a></span></li>",
				'accounting'=>"<li><span class''><a href=".$accoutning.">".$tr->translate("របាយការណ៏ គណនេយ្យ")."</a></span></li>",
				'rpt-student-list'=>"<li><span class''><a href='".$baseurl."/allreport/foundation/rpt-student-list'>".$tr->translate("បញ្ជីឈ្មោះនិស្សិត")."</a></span></li>",
				'rpt-student-info'=>"<li><span class''><a href='".$baseurl."/allreport/foundation/rpt-student-info'>".$tr->translate("ពត៌មានសិស្ស")."</a></span></li>",
				'poc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-exam-degree'>".$tr->translate('បញ្ជីរាយនាមបេក្ខជនប្រលង')."</a></li>",
				'legal-document'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-final-exams'>".$tr->translate("បេក្ខជនប្រលងជាប់ជាស្ថាពរ")."</a></li>",
				'rfm'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-stuid'>".$tr->translate('បេក្ខជនបានធ្វើកាតរ')."</a></li>",
				'pam'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-foundation'>".$tr->translate("បេក្ខជនបានធ្វើកាតរ")."</a></li>",
				'prc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-drop-out'>".$tr->translate("បេក្ខជនប្រលងជ្រើសរើសចូលរៀន")."</a></li>",
				'budget-regulation'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-total-attendance'>".$tr->translate("បញ្ជីសរុបអវត្តមាន")."</a></li>",
				'da'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("បញ្ជីស្រង់ពិន្ទសំរាប់គ្រូ")."</a></li>",
				'asd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-student-attendance'>".$tr->translate("បញ្ជីស្រង់អវត្តមាន")."</a></li>",
				'asdf'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-amount-student'>".$tr->translate("បញ្ជីសរុបចំនួននិស្សិត")."</a></li>",
				//''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("REF_SOP")."</a></li>",
				'rpt-allresult'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-allresult'>".$tr->translate("បញ្ជីលទ្ទផលប្រលងប្រចាំឆ្នាំ")."</a></li>",
				''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-certificate'>".$tr->translate("ឆ្នាំសិក្សាមូលដ្ឋាន ")."</a></li>",
				'asasfd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-full-result'>".$tr->translate("ប្រាក់ចំណូលរបស់និស្សិត")."</a></li>",
				'rpt-daily'=>"<li><a href='".$baseurl."/allreport/receiptionist/rpt-daily'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//accounting
				'rpt-account-rec'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-account-rec'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-gep-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-gep-list'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-list'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-invoice'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-invoice'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-list-of-item'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-list-of-item'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part1'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part1'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part2'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part2'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-student-list-detail-part3'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part3'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-studentpayment'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-studentpayment'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				'rpt-tuition-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-tuition-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
			),	
			'setting'=>array(
						'label'=>'<li><a href="">'.$tr->translate("Label_SETTING").'</a></li>',
						//'profile'=>'<li><a href="">'.$tr->translate("COM_PROFILE").'</a></li>',
						'database'=>'<li><a href="">'.$tr->translate("DATA_BASE_SETTING").'</a></li>',
						'setting'=>'<li><a href="">'.$tr->translate("System_SETTING").'</a></li>',
							
				)
		); 
	?>
	<div id="header-left">
	<ul>
			<?php 
// 				$request=Zend_Controller_Front::getInstance()->getRequest();
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;					
			?>
	</ul>																
	</div>