<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Payment Late'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentpaymentlate','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">	
		<tr> 
			 <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->search['adv_search']?>" placeholder="Search" type="text" ></td>
			 <td> <?php echo $frm->getElement("service");?></td>
			 <td><input dojoType="dijit.form.DateTextBox" class="fullside" id="end_date" name="end_date" value="<?php echo $this->search['end_date']; ?>"  type="text"></td>
			 <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
</form>	
</div>
<style>
.hover:hover{background: #ddd;}
</style>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
									<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
										
										<tr>
											<td width="28%" align="left">
												<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td align="center" width="44%">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សបង់យឺត</strong><br />
												<span style="font-weight: bold;font-size: 11px;"> On &nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));?></span><br /><br />
											</td>
											<td width="28%" align="right">
												
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<td style="border: 1px solid #000;">&nbsp;No.&nbsp;</td>
														<td style="border: 1px solid #000;">Student Id</td>
														<td style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</td>
														<td style="border: 1px solid #000;">&nbsp;Sex&nbsp;</td>
														<td style="border: 1px solid #000;">&nbsp;Tel&nbsp;</td>
														<td style="border: 1px solid #000;">&nbsp;Receipt No&nbsp;</td>
														<td style="border: 1px solid #000;">Service Name</td>
														<td style="border: 1px solid #000;">Paid Date</td>
														<td style="border: 1px solid #000;">Validate</td>
														<td style="border: 1px solid #000;">Remain Days</td>
													</tr>
												<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
													$date1=date_create($row['end']);
// 													$date2=date_create(date('Y-m-d'));
													$date2=date_create($this->search['end_date']);
													$diff=date_diff($date1,$date2);
													$day=$diff->format("%R%a");
// 													echo $diff->format('%R'); // use for point out relation: smaller/greater
// 													echo $diff->days;
												?>
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
														<td style="border: 1px solid #000;"><?php echo $i;?></td>
														<td style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</td>
														<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
														<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></td>
														<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['tel'];?></td>
														<td style="border: 1px solid #000;"><?php echo $row['receipt'];?></td>
														<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></td>
														<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</td>
														<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</td>
														<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;">&nbsp;<?php echo abs($day);?> days</td>
 													</tr>
												<?php }}?>	 
												</table>	
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr >
											<td align="center" width="25%">
												<span style=" font-size: 14px;">Verified by</span>
											</td>
											<td  width="50%">
												&nbsp;
											</td>
											<td align="center"  width="25%">
												<span style=" font-size: 14px;text-align: right;">Prepared by</span>
											</td>
										</tr>
										
									</table>
							
			</div>		
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
</script>




