<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_GRADE"));
?>	
<?php  $frm_major= $this->frm_major;?>
<form  id='edit-major' action="<?php echo $this->url(array('module'=>'global','controller'=>'major','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">

<table cellspacing="10" width="50%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong style="font-size: 18px;"><?php echo $tr->translate("EDIT_GRADE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("NAME_EN")?></td>
							<td> <?php echo $frm_major->getElement("major_enname");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td> <?php echo $frm_major->getElement("major_khname");?></td>
						</tr>
						<tr>
							<td> <?php echo $tr->translate("SHORTCUT");?></td>
							<td> <?php echo $frm_major->getElement("shortcut");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE")?></td>
							<td><?php echo $frm_major->getElement("dept");?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS");?></td>
							<td><?php echo $frm_major->getElement("status");?></td>
						</tr>
						<tr>
							<td colspan="2"><?php echo $frm_major->getElement("major_id");?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"major",'action'=>'index'),null,true); ?>';" />
								<input type="submit"  label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton" dojoType="dijit.form.Button" 
							 		iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>