<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	
	dojo.ready(function(){ 
		addRow();
	});	

</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("YEARS");?></td>
							<td><?php echo $register->getElement('study_year');?></td>
							<td><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<select class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
									<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
										<option value="<?php echo $row['stu_id']?>"><?php echo $row['stu_code']?></option>
									<?php }?>
								</select>
							</td>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
						   
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
						    <td><?php echo $tr->translate("NOT");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
							<td><?php echo $tr->translate("CHAR_PRICE");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('char_price');?></td>
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;" cellpadding="10" cellspacing="10" >
									<tr>
										<td >Total Payment</td>
										<td align="right"><input class="fullside" type="text" required="true" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("BOOKS");?></td>
										<td align="right"><input class="fullside" type="text" required="true" name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input class="fullside" type="text" readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("ប្រាក់អាប់");?></td>
										<td align="right"><input class="fullside" type="text" readonly="readonly" name="total_return" id="total_return" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="រក្សាទុក"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
								
								 <input type="button" value="បោះពុម្ព" label="បោះពុម្ព" id="print" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
	
	dojo.byId("lbl_khname").innerHTML = dijit.byId("kh_name").get('value');
	dojo.byId("lbl_enname").innerHTML = dijit.byId("en_name").get('value');
	dojo.byId("lbl_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
	dojo.byId("lbl_stuid").innerHTML = dijit.byId("studentid").attr('displayedValue');
	dojo.byId("lbl_recieptno").innerHTML = dijit.byId("reciept_no").get('value');
	var total = dijit.byId("grand_total").get('value');
	var recieve = dijit.byId("total_received").get('value');
	var balance_due = dijit.byId("total_balance").get('value');
	var toral_return = dijit.byId("total_return").get('value');
	

	
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	template="";
		 temp='<table class="collape tablesorter" border="1" align="center" style=" width: 100%; padding: 0px; margin: 0px; border-collapse: collapse; white-space:nowrap; border: 1px solid #000; font-size:10px;  " id="table">'
		      temp+='<tr style="background:#ccc; font-size:10px; "><th><?php echo $tr->translate("NO");?></th>';
		      temp+='<th><?php echo $tr->translate("Description");?></th>';
		      temp+='<th><?php echo $tr->translate("Payment Term");?></th>';
		      temp+='<th><?php echo $tr->translate("Price");?></th>';
		      temp+='<th><?php echo $tr->translate("Amount");?></th>';
		      temp+='<th><?php echo $tr->translate("Discount");?></th>';
		      temp+='<th><?php echo $tr->translate("Sub Total");?></th></tr>';
 
			    i=1;  for(var n = 0; n < rowIDArray.length; n++) {
			     
		      temp+='<tr style=" font-size:10px;height: 23px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("service_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("term_"+rowIDArray[n]).attr('displayedValue')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("qty_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("discount_"+rowIDArray[n]).get('value')+'%</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';
		      i++;
		     }
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="5"></td><td style="border:1px solid #000; padding-left: 10px;" >Total Payment</td><td style="border:1px solid #000; padding-left: 10px;">$ '+total+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="5"></td><td style="border:1px solid #000; padding-left: 10px;">Recieve Amount</td><td style="border:1px solid #000; padding-left: 10px;">$ '+recieve+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="5"></td><td style="border:1px solid #000; padding-left: 10px;">Balance Due</td><td style="border:1px solid #000; padding-left: 10px;">$ '+balance_due+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="5"></td><td style="border:1px solid #000; padding-left: 10px;">Return Amount</td><td style="border:1px solid #000; padding-left: 10px;">$ '+toral_return+'</td></tr>';
		    temp+='</table>';
		    dojo.byId('t_amountmoneytype').innerHTML = temp;

		dijit.byId("popup_invoice").show();	
		
	}
	
}
</script>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" id="popup_invoice" >
		<div id="divPrint" style=" width: 21cm; height: 12cm ; padding: 0px; margin: 0px;">
			<table style="background:#fff; margin: 0 auto; width: 21cm;height: 12cm; padding: 1cm; margin: 0 auto;" align="center">
							<tr style="font-size: 13px; ">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black; color:#000; font-size: 13px; font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black; color:#000; font-size: 13px; font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
								<td width="25%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style=" font: bold 13px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
								</td>
								<td align="right" width="20%">
								</td>
							</tr>
							<tr>
								<td width="25%" align="left">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student Name  : <label id="lbl_khname"></label> <label  id="lbl_enname"></label></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Sex  : <label id="lbl_sex"></label></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student ID  : <label id="lbl_stuid"></label></strong><br />
								</td>
								<td>&nbsp;</td>
								<td width="25%" align="left" style=" padding-right: 20px;">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Reciept N.o : <label id="lbl_recieptno"></label></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Date Paid : <?php echo date("d-m-Y")?></strong><br />
								</td>
							</tr>
							<tr>
								<td colspan="3">
                                    	 <div id="t_amountmoneytype"></div>
								</td>
							</tr>
							
							<tr>
									<td colspan="2">&nbsp;</td>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">អ្នកទទួល   <?php echo $this->rr['USER'];?></strong><br />
									</td>
							</tr>
							<tr>
									<td></td>
									<td></td>
									<td align="left">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ហត្ថលេខា </strong><br />
									</td>
							</tr>
						</table>
	</div>
	<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
</div>
</div>	
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
<?php $keycode = $this->keycode;?>


<script>
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_invoice").hide();
}

var template = '';

var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("TOTAL");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="23%" align="center">'+no+'</td>';
			template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			

			
			template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;">';
				<?php foreach($this->payment_term as $key => $value){?>
					template+='<option value="'+<?php echo $key?>+'"><?php echo $value;?></option>';
				<?php }?>
			template+='</select></td>';
			column = 0;
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" readonly="readonly" name="total_'+col+'" id="total_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" onkeyup="calculateDiscount('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	dijit.byId('total_'+index).attr('value',total);
	calculateDiscount(index);
}
function calculateDiscount(index){
	total = dijit.byId('total_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	discount=isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-discount);
	netTotal();
}
function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
	}
	dijit.byId('grand_total').attr('value',netTotal);
	dijit.byId('total_received').attr('value',netTotal);
	//$('#grand_total').val(netTotal);
	//$('#total_received').val(netTotal);
	calculatBalance();
}
function calculatBalance(){
	totalreceived = dijit.byId('total_received').get('value');
	grand_total = dijit.byId('grand_total').get('value');
	dijit.byId('total_return').attr('value',totalreceived-grand_total);
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					alert(err);
				}
			});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-price')); ?>";
function getservicefee(key){
			services = dijit.byId('service_'+key).get('value');
			term = dijit.byId('term_'+key).get('value');
			dojo.xhrPost({
				url:url_service_fee,
				content:{
					'term':term,
					'service':services,
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("price_"+key).attr("value",data.price_fee);
					//dijit.byId("total_"+key).attr("value",data.price_fee);
					calculateTotal(key);

				},
				error: function(err) {
					alert(err);
				}
			});
}
function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>


