<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_SERVICE_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	

	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id){
			dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					 dijit.byId('stu_id').attr('value',data);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}
	function paymentTerm(){
		study_year=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		levele=dijit.byId('grade').get('value');
		if(study_year!='' && payment_term !='' && levele !=''){
			getPaymentTerms(study_year,levele,payment_term);
		}
	}
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var major_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

	dojo.addOnLoad(function(){
		   // document.musicPrefs.other.value="Afrobeat";
			//getStudentBYId();
		});

		
	
	var url_getstu_info = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-studentinfo')); ?>';
	function getStudentBYId(){
		   student_id = dijit.byId("stu_id").get('value');
		   if(student_id==''){
			   return false;
			   }
				dojo.xhrPost({
				   content : {'student_card':  student_id},
				    url: url_getstu_info,			    
					handleAs:"json",
				    load: function(response) {	
					    dijit.byId("kh_name").attr('value',response.stu_khname);
					    dijit.byId("en_name").attr('value',response.stu_enname);
					    dijit.byId('sex').set('value', response.sex);
					    dijit.byId("phone").attr('value',response.phone);
					    dijit.byId("metion").attr('value',response.mention);
					    dijit.byId('year').attr('value',response.year);
					    dijit.byId('degree').set('value', response.degree);
					    dijit.byId('batch').set('value',response.batch);
					    dijit.byId('dept').set('value',response.faculty_id);
					    dijit.byId('session').set('value',response.session);
				    },
				    error: function(e) {
					    alert(e);
				    }
				});
	}
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("YEARS");?></td>
							<td><?php echo $register->getElement('study_year');?></td>
							<td><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?><input type="hidden" id="id" name="id" value="<?php echo $this->row['id'];?>" /></td>
							<td>
								<select class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
									<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
										<option value="<?php echo $row['stu_id']?>" <?php if($row['stu_id']==$this->row['student_id']) echo 'selected="selected"';?>><?php echo $row['stu_code']?></option>
									<?php }?>
								</select>
							</td>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
						   
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
						    <td><?php echo $tr->translate("NOT");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
							<td><?php echo $tr->translate("CHAR_PRICE");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('char_price');?></td>
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input class="fullside" type="text" onkeyup="calculatBalanceAndReturn();" value="<?php //echo $this->row['total_payment'];?>"  required="true" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("BOOKS");?></td>
										<td align="right"><input class="fullside" type="text" onkeyup="calculatBalanceAndReturn();" value="<?php //echo $this->row['paid_amount'];?>" required="true" name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['balance_due'];?>" readonly="readonly" name="total_balance" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("ប្រាក់អាប់");?></td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['return_amount'];?>" readonly="readonly" name="total_return" id="total_return" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="រក្សាទុក"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="រក្សាទុក & បោះពុម្ព" label="បោះពុម្ព" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
	
	dojo.byId("lbl_khname").innerHTML = dijit.byId("kh_name").get('value');
	dojo.byId("lbl_enname").innerHTML = dijit.byId("en_name").get('value');
	dojo.byId("lbl_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
	dojo.byId("lbl_stuid").innerHTML = dijit.byId("studentid").attr('displayedValue');
	dojo.byId("lbl_recieptno").innerHTML = dijit.byId("reciept_no").get('value');
	var total = dijit.byId("grand_total").get('value');
	var recieve = dijit.byId("total_received").get('value');
	var balance_due = dijit.byId("total_balance").get('value');
	var toral_return = dijit.byId("total_return").get('value');
	

	
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	template="";
		 temp='<table class="collape tablesorter" border="1" align="center" style=" width: 100%; padding: 0px; margin: 0px; border-collapse: collapse; white-space:nowrap; border: 1px solid #000; font-size:10px;  " id="table">'
			  temp+='<tr style="background:#ccc; font-size:10px; "><th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("លេខ/No");?></strong></th>';
	    	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("ឈ្មោះសេវាកម្ម / Service Name");?></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("បង់ជា / Payment Term");?></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("តំលៃ / Price");?></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("ចំនួន / Amount");?></strong></th>';
	       	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("បញ្ចុះតំលៃ / Discount");?></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("តំលៃសរុប​ / Sub Total");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("សុពលភាព / Validate");?></strong></th></tr>';
			    i=1;  for(var n = 0; n < rowIDArray.length; n++) {
			     
		      temp+='<tr style=" font-size:10px;height: 23px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
		      temp+='<td align="left" style="border:1px solid #000;">&nbsp;&nbsp;'+dijit.byId("service_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
		      temp+='<td align="left" style="border:1px solid #000;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 9px;">&nbsp;&nbsp;'+dijit.byId("term_"+rowIDArray[n]).attr('displayedValue')+'</span></td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("qty_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("discount_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';

		      var a = new Date(dijit.byId("validate_"+rowIDArray[n]).get('value'));
			  mm = a.getMonth()+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 var epx_date = dd + '-' + mm + '-' + y ;

			
		      temp+='<td style="border:1px solid #000;"> '+epx_date+'</td>';
		      i++;
		      temp+='</tr>';
		     }
			  temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="6"></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ទឹកប្រាក់ត្រូវបង់ / Total Payment</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+total+'</td></tr>';
			  temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="6"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;color:red;">** ប្រាក់ដែលបង់រួចមិនអាចដកវិញបានទេ</strong></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ទឹកប្រាក់ទទួលបាន / Recieve Amount</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+recieve+'</td></tr>';
			  temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="6"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 13px;color:red;">** Nonrefundable</strong></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ប្រាក់នៅខ្វះ / Balance Due</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+balance_due+'</td></tr>';
			  temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="6"></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ប្រាក់អាប់ / Return Amount</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+toral_return+'</td></tr>';
		    temp+='</table>';
		    dojo.byId('t_amountmoneytype').innerHTML = temp;

		dijit.byId("popup_invoice").show();	
		
	}
	
}
</script>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" id="popup_invoice" >
		<div id="divPrint" style=" width: 23cm; height: 12cm ; padding: 0px; margin: 0px;">
			<table style=" background:#fff; margin: 0 auto; width: 21cm; height: 12cm; padding: 1cm; ">
							<tr>
								<td width="25%" align="left">
								</td>
								<td align="center">
									<strong style=" font: bold 15px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 15px;padding-right: 10px;">OFFICAIL RECEIPT</strong><br >
								</td>
								<td align="right" width="20%">
								</td>
							</tr>
							<tr>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;">
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">អត្តលេខសិស្ស  : </strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;">Student ID &nbsp;&nbsp;&nbsp;</strong>
											</td>
											<td >
												<label id="lbl_stuid"></label>
											</td>
											
										</tr>
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ឈ្មោះសិស្ស :</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">Student Name </strong>
											</td>
											<td ><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"><label id="lbl_khname"></label></strong> - <label id="lbl_enname"></label></td>
										</tr>
										<tr>
											<td ><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ភេទ / Sex : </strong></td>
											<td >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"><label id="lbl_sex"></label></strong>
											</td>
										</tr>
									</table>
								</td>
								<td width="30%">
									&nbsp;
								</td>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;">
										<tr>
											<td width="20%" style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">វិក័យប័ត្រលេខ​  :  </strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">Reciept N.o  </strong>
											</td>
											
											<td width="20%" >
												<b><label id="lbl_recieptno"> </label></b>
											</td>
										</tr>
										<tr>
											<td width="20%" style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">ថ្ងៃបង់ :  </strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">Date Paid  </strong>
											</td>
											<td width="80%"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"><?php echo Zend_Date::now();?></span></td>
										</tr>
										<tr>
											<td colspan="2"></td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
                                    	 <label id="t_amountmoneytype"></label>
								</td>
							</tr>
							
							<tr>
								<td align="left">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-left: 50px;">អ្នកទទួល   <?php echo $this->rr['USER'];?></strong><br />
								</td>
								<td>&nbsp;</td>
								<td align="right">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-right: 80px;">ហត្ថលេខា </strong><br />
								</td>
							</tr>
							<tr>
								<td colspan="3"> <div style="padding-left: 57px;font-family: Khmer OS Battambang;color:#000;"><?php $session_user=new Zend_Session_Namespace('auth'); $username = $session_user->first_name;echo $username; ?></div></td>
							</tr>
						</table>
	</div>
	<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
</div>
</div>

<script>
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_invoice").hide();
}

var template = '';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("TOTAL");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="23%" align="center">'+no+'</td>';
			template+='<td><select onchange="getservicefee('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			//template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;"><option value="1">Monthly</option><option value="2">Quarter</option><option value="3">Semester</option><option value="4">Yearly</option></select></td>';
			template+='<td><select onchange="getservicefee('+col+');getValidate('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;">';
				<?php foreach($this->payment_term as $key => $value){?>
					template+='<option value="'+<?php echo $key?>+'"><?php echo $value;?></option>';
				<?php }?>
			template+='</select></td>';
			column = 0;
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');getValidate('+col+');" name="qty_'+col+'" value="" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
			//template+='<td> <input type="text" required="true" readonly="readonly" name="total_'+col+'" value="" id="total_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="calculateDiscount('+col+');" value="<?php echo 0;?>"  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true"  name="validate_'+col+'" id="validate_'+col+'" dojoType="dijit.form.DateTextBox" style="width:200px;" /><label id="validate"></label></td>';
			template+='<td> <input type="text" required="true" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	//dijit.byId('total_'+index).attr('value',total);
	calculateDiscount(index);
}
function calculateDiscount(index){

	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	
	//total = dijit.byId('total_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	discount=isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-discount);
	netTotal();
}
function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
	}
	//alert(netTotal);
	
	dijit.byId('grand_total').attr('value',netTotal);
	//dijit.byId('total_received').attr('value',netTotal);
	//$('#grand_total').val(netTotal);
	//$('#total_received').val(netTotal);
	calculatBalanceAndReturn();
}
function calculatBalanceAndReturn(){
	totalreceived = dijit.byId('total_received').get('value');
	grand_total = dijit.byId('grand_total').get('value');

	if(totalreceived>grand_total){
		dijit.byId('total_return').attr('value',totalreceived-grand_total);
		dijit.byId('total_balance').attr('value',0);
	}
	else{
		dijit.byId('total_balance').attr('value',grand_total-totalreceived);
		dijit.byId('total_return').attr('value',0);
	}
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					alert(err);
				}
			});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-price')); ?>";
function getservicefee(key){
			services = dijit.byId('service_'+key).get('value');
			term = dijit.byId('term_'+key).get('value');
			dojo.xhrPost({
				url:url_service_fee,
				content:{
					'term':term,
					'service':services,
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("price_"+key).attr("value",data.price_fee);
					//dijit.byId("total_"+key).attr("value",data.price_fee);
					calculateTotal(key);

				},
				error: function(err) {
					alert(err);
				}
			});
}

dojo.ready(function(){
	 initailize();
	 getStudentInfo();
	 dijit.byId('study_year').attr('value','<?php echo $this->row['year']?>');
	 dijit.byId('reciept_no').attr('value','<?php echo $this->row['receipt_number']?>');
	 dijit.byId('not').attr('value','<?php echo $this->row['note']?>');
	 dijit.byId('char_price').attr('value','<?php echo $this->row['amount_in_khmer']?>');
	 dijit.byId('total_balance').attr('value','<?php echo $this->row['balance_due']?>');
	 dijit.byId('total_return').attr('value','<?php echo $this->row['return_amount']?>');
	 dijit.byId('total_received').attr('value','<?php echo $this->row['receive_amount']?>');
	 dijit.byId('grand_total').attr('value','<?php echo $this->row['total_payment']?>');
});
function initailize(){
	<?php if(!empty($this->rows)){
		foreach($this->rows as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
		
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("VALIDATE");?></th>';
		temp+='<th><?php echo $tr->translate("REMARK");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="23%" align="center">'+no+'</td>';
		template+='<td><select onchange="getservicefee('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
		//template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;"><option value="1">Monthly</option><option value="2">Quarter</option><option value="3">Semester</option><option value="4">Yearly</option></select></td>';
		template+='<td><select onchange="getservicefee('+col+');getValidate('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;">';
			<?php foreach($this->payment_term as $key => $value){?>
				template+='<option value="'+<?php echo $key?>+'"><?php echo $value;?></option>';
			<?php }?>
		template+='</select></td>';
		column = 0;
		template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
		template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');getValidate('+col+');" name="qty_'+col+'" value="<?php //echo $this->row['qty'];?>" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
		//template+='<td> <input type="text" required="true" readonly="readonly" name="total_'+col+'" value="<?php //echo $this->row['amount'];?>" id="total_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
		template+='<td> <input type="text" required="true" onkeyup="calculateDiscount('+col+');" value="<?php //echo $this->row['discount_fix'];?>"  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
		template+='<td> <input type="text" required="true" readonly="readonly" name="subtotal_'+col+'" value="<?php //echo $this->row['total_payment'];?>" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
		template+='<td> <input type="text" required="true"  name="validate_'+col+'" id="validate_'+col+'" dojoType="dijit.form.DateTextBox" style="width:200px;" /><label id="validate"></label></td>';
		template+='<td> <input type="text" required="true" name="remark'+col+'" value="<?php //echo $this->row['note1'];?>" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	
	dijit.byId('service_'+col).attr('value','<?php echo $row['service_id']?>');
	dijit.byId('term_'+col).attr('value','<?php echo $row['payment_term']?>');
	dijit.byId('price_'+col).attr('value','<?php echo $row['fee']?>');
	dijit.byId('qty_'+col).attr('value','<?php echo $row['qty']?>');
	dijit.byId('validate_'+col).attr('value','<?php echo $row['validate']?>');
	dijit.byId('discount_'+col).attr('value','<?php echo $row['discount_fix']?>');
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	<?php } }?>
}

function getValidate(key){
	//alert(1);
	//amount_month=dijit.byId('duration').get('value');
	 amount= dijit.byId('qty_'+key).get('value');
	 //start_date = dijit.byId("study_start").get('value');
	 term = dijit.byId('term_'+key).get('value');

	 var dNow = new Date();
	 var localdate= (dNow.getMonth()+1) + '/' + dNow.getDate() + '/' + dNow.getFullYear();
	 
	// alert(localdate);
	 
	 if(term==1){
		 var a = new Date(localdate);
		  mm = a.getMonth()+amount+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==2){
		 var a = new Date(localdate);
		  mm = a.getMonth()+(amount*3)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==3){
		 var a = new Date(localdate);
		  mm = a.getMonth()+(amount*6)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==4){
		 var a = new Date(localdate);
		  mm = a.getMonth()+(amount*12)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }

	 var a = new Date(start_date);
	  mm = a.getMonth()+amount_month+1;

	 var dd = a.getDate();
	  if(dd<10){
	   dd = "0"+dd;
	 }
	  if(mm<10){
	   mm = "0"+mm;
	 }
	 var y = a.getFullYear();
	 var epx_date = y + '-' + mm + '-' + dd ;

	 //alert(epx_date);
	 dijit.byId('start_end').attr('value',epx_date);
}

function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>
	
	