<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	

	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id){
			dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					 dijit.byId('stu_id').attr('value',data);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}
	function paymentTerm(){
		study_year=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		levele=dijit.byId('grade').get('value');
		if(study_year!='' && payment_term !='' && levele !=''){
			getPaymentTerms(study_year,levele,payment_term);
		}
	}
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var major_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

	dojo.addOnLoad(function(){
		   // document.musicPrefs.other.value="Afrobeat";
			//getStudentBYId();
		});

		
	
	var url_getstu_info = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-studentinfo')); ?>';
	function getStudentBYId(){
		   student_id = dijit.byId("stu_id").get('value');
		   if(student_id==''){
			   return false;
			   }
				dojo.xhrPost({
				   content : {'student_card':  student_id},
				    url: url_getstu_info,			    
					handleAs:"json",
				    load: function(response) {	
					    dijit.byId("kh_name").attr('value',response.stu_khname);
					    dijit.byId("en_name").attr('value',response.stu_enname);
					    dijit.byId('sex').set('value', response.sex);
					    dijit.byId("phone").attr('value',response.phone);
					    dijit.byId("metion").attr('value',response.mention);
					    dijit.byId('year').attr('value',response.year);
					    dijit.byId('degree').set('value', response.degree);
					    dijit.byId('batch').set('value',response.batch);
					    dijit.byId('dept').set('value',response.faculty_id);
					    dijit.byId('session').set('value',response.session);
				    },
				    error: function(e) {
					    alert(e);
				    }
				});
	}
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("YEARS");?></td>
							<td><?php echo $register->getElement('study_year');?></td>
							<td><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?><input type="hidden" id="id" name="id" value="<?php echo $this->row['id'];?>" /></td>
							<td>
								<select class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
									<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
										<option value="<?php echo $row['stu_id']?>" <?php if($row['stu_id']==$this->row['student_id']) echo 'selected="selected"';?>><?php echo $row['stu_code']?></option>
									<?php }?>
								</select>
							</td>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
						   
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
						    <td><?php echo $tr->translate("NOT");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
							<td><?php echo $tr->translate("CHAR_PRICE");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('char_price');?></td>
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;" cellpadding="10" cellspacing="10" >
									<tr>
										<td >Total Payment</td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['total_payment'];?>"  required="true" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("BOOKS");?></td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['paid_amount'];?>" required="true" name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['balance_due'];?>" readonly="readonly" name="total_balance" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("ប្រាក់អាប់");?></td>
										<td align="right"><input class="fullside" type="text" value="<?php //echo $this->row['return_amount'];?>" readonly="readonly" name="total_return" id="total_return" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="រក្សាទុក"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="រក្សាទុក & បោះពុម្ព" label="រក្សាទុក & បោះពុម្ព" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
			/*dojo.byId("lb_term").innerHTML = dijit.byId("payment_term").attr('displayedValue');
			dojo.byId("lb_enroll_id").innerHTML = dijit.byId("reciept_no").get('value');
			 var d = dojo.byId("start_date").value.split('/');
			 dojo.byId("lb_term_start").innerHTML = d[1] + "/" + d[0] +"/"+d[2];
			 var d = dojo.byId("end_date").value.split('/');
			 dojo.byId("lb_term_end").innerHTML = d[1] + "/" + d[0] +"/"+d[2];
	 dojo.byId("lb_student").innerHTML = dijit.byId("en_name").get('value');
	 dojo.byId("lb_student_id").innerHTML = dijit.byId("stu_id").get('value');
	 dojo.byId("lb_level").innerHTML = dijit.byId("grade").attr('displayedValue');
	 
	 dojo.byId("lb_time_study").innerHTML = dijit.byId("from_time").attr('displayedValue')+"-"+dijit.byId("to_time").attr('displayedValue');
	 dojo.byId("lb_room").innerHTML = dijit.byId("room").attr('displayedValue');
	 dojo.byId("lb_note").innerHTML = dijit.byId("not").get('value');
	 dojo.byId("lb_course_cost").innerHTML ="$"+dijit.byId("tuitionfee").get('value').toFixed(2);
	 dojo.byId("lb_discount").innerHTML ="$"+dijit.byId("discount").get('value')+"%";
	 dojo.byId("lb_total").innerHTML ="$"+dijit.byId("total").get('value');
	 dojo.byId("lb_book").innerHTML ="$"+dijit.byId("books").get('value').toFixed(2);
	 dojo.byId("lb_balance").innerHTML ="$"+dijit.byId("remaining").get('value');*/
		dijit.byId("studentpaymentreceipt").show();	
		
	}
	
}
</script>
<div class="dijitHidden">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:7cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="studentpaymentreceipt" >
		 <div class="header">
		     <table     bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="width: 21cm;  font-size:14px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
		          <tr>
		              <td colspan="8"  align="center"><strong style="font-family:'Khmer OS Muol';font-size: 20px;color: rgb(47, 70, 149);"> សាលារៀន &nbsp;<font style="color: rgb(246, 86, 74);">អាស៊ាន </font>&nbsp;ហ៊ែរីថេជ</strong>
		              ​​​​​<br/><strong style="font-size: 20px;font-weight:bold;color: rgb(47, 70, 149);">ASEAN <font style="color: rgb(246, 86, 74);">HERITAGE</font> SCHOOL</strong>
		              </td>
		          </tr>
		     </table>
		</div>
		<div id="divPrint" style="width: 21cm; height: 12cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -5px;}
​​               .print td{ font:bold 11px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			</style>	
			<table   class="print" bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="width: 21cm;height: 12cm; font-size:12px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
				<tr>
				    <td   style="font:bold 20px 'Kh Muol';" align="center"><u><b><strong>បង្កាន់ដៃបង់ប្រាក់</strong></b></u>
				        <br/><strong style="font-size: 20px;font-weight:bold">OFFICAL RECEIPT</strong>
				    </td>
				</tr>
				<tr>
				    <td  align="left"><?php echo $tr->translate("YEARS");?></td>
				    
				    <td  align="left"><?php echo $tr->translate("RECEIPT_NO");?></td>
				    <td width="200px" ><input dojoType="dijit.form.TextBox"  class="fullside" id="receipt_no" name="receipt_no"  type="text"></td>
				    
				</tr>
				
				
				
				<tr>
				    <td  align="left" class="khmerbold">
				     *Note: All fees are not transferable or refundable . 
				    </td>
				</tr>
			</table>
		</div>
		<div class="footer_re"  >
		<table  bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="width: 21cm;  font-size:14px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;" >
		    <tr>
				 <td  > 
				       <hr style="background: rgba(251, 239, 13, 0.87) none repeat scroll 0% 0%; height: 4px; border: medium none rgb(240, 255, 0);"/>
				       <p class=" khmerbold">អាគារលេខ១៤៧​K ផ្លូវ៥៩៨ សង្កាត់ទូលសង្កែ ខណ្ឌឬស្សីកែង រាជធានីភ្នំពេញ ព្រះរាជាណាចក្រកម្ពុជា</p>
				 </td>
				</tr>
		</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>

<script>
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}

var template = '';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("TOTAL");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="23%" align="center">'+no+'</td>';
			template+='<td><select onchange="getservicefee('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;"><option value="1">Monthly</option><option value="2">Quarter</option><option value="3">Semester</option><option value="4">Yearly</option></select></td>';
			column = 0;
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="qty_'+col+'" value="" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" readonly="readonly" name="total_'+col+'" value="" id="total_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="calculateDiscount('+col+');" value=""  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text" required="true" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	dijit.byId('total_'+index).attr('value',total);
	calculateDiscount(index);
}
function calculateDiscount(index){
	total = dijit.byId('total_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	discount=isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-discount);
	netTotal();
}
function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
	}
	$('#grand_total').val(netTotal);
	$('#total_received').val(netTotal);
	calculatBalance();
}
function calculatBalance(){
	totalreceived = dijit.byId('total_received').get('value');
	grand_total = dijit.byId('grand_total').get('value');
	dijit.byId('total_return').attr('value',totalreceived-grand_total);
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					alert(err);
				}
			});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-price')); ?>";
function getservicefee(key){
			service = dijit.byId('service_'+key).get('value');
			term = dijit.byId('term_'+key).get('value');
			dojo.xhrPost({
				url:url_service_fee,
				content:{
					'term':term,
					'service':service,
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("price_"+key).attr("value",data.price_fee);
					//dijit.byId("total_"+key).attr("value",data.price_fee);
					calculateTotal(key);

				},
				error: function(err) {
					alert(err);
				}
			});
}

dojo.ready(function(){
	 initailize();
	 getStudentInfo();
	 dijit.byId('study_year').attr('value','<?php echo $this->row['year']?>');
	 dijit.byId('reciept_no').attr('value','<?php echo $this->row['receipt_number']?>');
	 dijit.byId('not').attr('value','<?php echo $this->row['note']?>');
	 dijit.byId('char_price').attr('value','<?php echo $this->row['amount_in_khmer']?>');
});
function initailize(){
	<?php if(!empty($this->rows)){
		foreach($this->rows as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("TOTAL");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
		temp+='<th><?php echo $tr->translate("REMARK");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="23%" align="center">'+no+'</td>';
		template+='<td><select onchange="getservicefee('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
		template+='<td><select onchange="getservicefee('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:120px;"><option value="1">Monthly</option><option value="2">Quarter</option><option value="3">Semester</option><option value="4">Yearly</option></select></td>';
		column = 0;
		template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
		template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="qty_'+col+'" value="<?php //echo $this->row['qty'];?>" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
		template+='<td> <input type="text" required="true" readonly="readonly" name="total_'+col+'" value="<?php //echo $this->row['amount'];?>" id="total_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
		template+='<td> <input type="text" required="true" onkeyup="calculateDiscount('+col+');" value="<?php //echo $this->row['discount_fix'];?>"  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="subsub"></label></td>';
		template+='<td> <input type="text" required="true" readonly="readonly" name="subtotal_'+col+'" value="<?php //echo $this->row['total_payment'];?>" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:100px;" /><label id="qty"></label></td>';
		template+='<td> <input type="text" required="true" name="remark'+col+'" value="<?php //echo $this->row['note1'];?>" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	
	dijit.byId('service_'+col).attr('value','<?php echo $row['service_id']?>');
	dijit.byId('term_'+col).attr('value','<?php echo $row['payment_term']?>');
	dijit.byId('price_'+col).attr('value','<?php echo $row['fee']?>');
	dijit.byId('qty_'+col).attr('value','<?php echo $row['qty']?>');
	dijit.byId('total_'+col).attr('value','<?php echo $row['amount']?>');
	dijit.byId('discount_'+col).attr('value','<?php echo $row['discount_fix']?>');
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	<?php } }?>
}


function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>