<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_SERVICE_PAYMENT'));
	$frm =  $this->form_search;
?>
<meta charset="utf-8">
 <form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
					   <table style="width:100%">
						  <tr> 
							  <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="Search" type="text" ></td>
							  <td> <?php echo $frm->getElement("study_year");?></td>
							  <td> <?php echo $frm->getElement("grade");?></td>
							  <td> <?php echo $frm->getElement("service");?></td>
							  <td> <?php echo $frm->getElement("pay_term");?></td>
					   	  </tr>
					   	  <tr>
					   	  	   <td> <input dojoType="dijit.form.DateTextBox" class="fullside" id="start_date" name="start_date" value="<?php  if(empty($this->adv_search['start_date'])){echo date('Y-m-d');}else   echo $this->adv_search['start_date']; ?>"  type="text"></td>
					           <td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" value="<?php if(empty($this->adv_search['end_date'])){ echo date('Y-m-d');}else echo $this->adv_search['end_date'];?>" type="text"></td>
							   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
					   </table>
 </form>

<?php echo $this->list; ?>




















