  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  $rpt_student_change_group=$this->url(array('module'=>'allreport','controller'=>'studentchangegroup','action'=>'rpt-student-change-group'), null, true);
  $rpt_student_drop=$this->url(array('module'=>'allreport','controller'=>'studentdrop','action'=>'rpt-student-drop'), null, true);
  $rpt_student=$this->url(array('module'=>'allreport','controller'=>'student','action'=>'rpt-student'), null, true);
  $rpt_loancollect=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loancollect'), null, true);
  $rpt_dailypayment=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-payment'), null, true);
  $rpt_loanincome=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-income'), null, true);
  $rpt_loan_late=$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-loan-late'), null, true);
  
  
  
  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  	
  		<li><a href="<?php //echo $rpt_student_change_group;?>"><?php echo $tr->translate('RPT_STUDENT_GROUP');?></a></li>
  		<li><a href="<?php echo $rpt_student_change_group;?>"><?php echo $tr->translate('RPT_STUDENT_CHANGE_GROUP');?></a></li>
  		<li><a href="<?php echo $rpt_student_drop;?>"><?php echo $tr->translate('RPT_STUDENT_DROP');?></a></li>
  		<li><a href="<?php echo $rpt_loanincome;?>"><?php echo $tr->translate('RPT_ATTENDENT');?></a></li>
  		<li><a href="<?php echo $rpt_student;?>"><?php echo $tr->translate('RPT_REGISTER');?></a></li>
  		
  		
  		
  		<!--<li><a href="#"><?php //echo $tr->translate('LOAN_DISBURSE');?></a></li> -->
  	</ul>
  </div>
  <div style="clear: both;"></div>
  
  
  