<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	echo $this->headTitle('SRMS | Student Exam Fundation Year'); 
	
?>	
<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
								<tr style="font-size: 13px;">
										<td colspan="2"></td>
										<td align="right">
											<strong></strong><br />
											<strong></strong><br />
										</td>
									</tr>
									<tr>
										<td width="20%" align="left">
											<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
										</td>
										<td width="20%" align="center">
											<strong>ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
											<strong>ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
											<strong style="font-family: Tacteing;">7</strong><br />
											<strong>បញ្ជីរាយនាមសិស្ស</strong><br />
											<strong></strong><br />
										</td>
										<td width="20%" align="right">
											<strong>ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
											<strong>សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
										</td>
										
									</tr>
									<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th rowspan="2">ល.រ</th>
												<th rowspan="2">អត្តលេខ</th>	
												<th rowspan="2">គោត្តនាម-នាម</th>
												<th rowspan="2">អក្សរឡាតាំង</th>
												<th rowspan="2">ភេទ</th>												
												<th rowspan="2">សញ្ចាតិ</th>
												<th rowspan="2">ថ្នាក់ទី</th>
												<th rowspan="2">កម្រិត</th>
												<th colspan="3">លេខទូរសព្ទ</th>
												<th rowspan="2" style="white-space: nowrap;">ថ្ងៃខែឆ្នាំកំណើត</th>
												<th rowspan="2">ទីកន្លែងកំណើត</th>
												<th rowspan="2">វេនសិក្សា</th>
												<th rowspan="2">កម្រិតសិក្សា</th>
												<th rowspan="2">អាសយដ្ឋានរបស់និស្សិត</th>
												<th rowspan="2">ផ្សេងៗ</th>
											</tr>
											<tr​​>
												<th align="center"​​><small>Personal</small></th>
												<th align="center"><small>Father</small></th>
												<th align="center"><small>mother</small></th>
											</tr><style> td{padding:0 3px; }</style>
											<?php  $i=0; foreach ($this->rs as $row){ $i++;?>
											<tr style="font-size:11px; height: 30px;" align="center">
												<td><?php echo $i;?></td>
												<td style="white-space: nowrap;"><?php echo $row['stu_code'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_khname'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_enname'];?></td>
												<td><?php echo $row['gender'];?></td>
												<td><?php echo $row['nationality'];?></td>
												<td><?php echo $row['grade'];?></td>
												<td><?php echo $row['level'];?></td>
												<td><?php echo $row['tel'];?></td>
												<td><?php echo $row['father_phone'];?></td>
												<td><?php echo $row['mother_phone'];?></td>
												<td><?php echo $row['dob'];?></td>
												<td><?php echo $row['address'];?></td>
												<td><?php echo $row['session'];?></td>
												<td><?php echo $row['degree'];?></td>
												<td ><?php echo $row['home_num'];?> <?php echo $row['street_num'];?> <?php echo $row['village_name'];?> <?php echo $row['commune_name'];?> <?php  echo $row['pro'];?></td>
												<td><?php echo $row['remark'];?></td>
											</tr>
											<?php }?>	
										</table>
										
									</td>
								</tr>
							</table>
		</div>
	</div>
