<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<!-- 		<select dojoType="dijit.form.FilteringSelect" id="searchby" name="searchby" placeholder="Search by ....." value="" type="text"> -->
<!-- 			<option value="0">All</option> -->
<!-- 			<option value="1">Student Code</option> -->
<!-- 			<option value="2">Student Name</option> -->
<!-- 			<option value="3">Degree</option> -->
<!-- 			<option value="4">Grade</option> -->
<!-- 			<option value="5">Session</option> -->
<!-- 		</select> -->
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
	<div style="border: 1px dotted #000;background: #fff;width:100%;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
								<tr>
									<td width="28%" >
										<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏ សិស្ស</strong><br />
									</td>
									<td width="28%" align="right">
										<strong>&nbsp;</strong>
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}
	
</style>
								<tr>
									<td colspan="3">
										<table cellpadding="4"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
											<tr style="font-size:9px; height: 20px;" align="center" >
												<th rowspan="2">No.</th>
												<th rowspan="2">Student Code</th>
												<th rowspan="2">Name</th>
												<th rowspan="2">Sex</th>
												<th rowspan="2">Nationality</th>
												<th rowspan="2">Tel</th>
												<th rowspan="2">Email</th>
												
												<th colspan="6">Address</th>
												<th colspan="3">Study Info</th>
												<th colspan="3">Father Info</th>					
												<th colspan="3">Mother Info</th>
												<th colspan="3">Guardian Info</th>
											</tr>
											<tr style="font-size:9px; height: 20px;" align="center" >
												<th >Home</th>
												<th >Str.</th>
												<th >Vil.</th>
												<th >Comm.</th>
												<th >Distr.</th>
												<th >Prov.</th>
											
												<th >Deg.</th>
												<th >Grade</th>
												<th >Sess.</th>
											
												<th >Name</th>
												<th >Job</th>
												<th >Phone</th>
												
												<th >Name</th>
												<th >Job</th>
												<th >Phone</th>
												
												<th >Name</th>
												<th >Job</th>
												<th >Phone</th>
											
											</tr>
											
											
											
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:9px; height: 23px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['stu_code'];?></th>
												<th align="left">&nbsp;<?php echo $row['name'];?>&nbsp;</th>
												<th ><?php echo $row['sex'];?></th>	
												<th ><?php echo $row['nationality'];?></th>
												<th ><?php echo $row['tel'];?></th>
												<th align="left"><?php echo $row['email'];?></th>
												
												<th ><?php echo $row['home_num'];?></th>
												<th ><?php echo $row['street_num'];?></th>
												<th ><?php echo $row['village_name'];?></th>					
												<th ><?php echo $row['commune_name'];?></th>
												<th ><?php echo $row['district_name'];?></th>
												<th ><?php echo $row['province'];?></th>	
												
												<th ><?php echo $row['degree'];?></th>
												<th align="left"><?php echo $row['grade'];?></th>
												<th ><?php echo $row['session'];?></th>	
												
												<th align="left"><?php echo $row['father_name'];?></th>
												<th align="left"><?php echo $row['father_job'];?></th>
												<th ><?php echo $row['father_phone'];?></th>	
												
												<th align="left"><?php echo $row['mother_name'];?></th>
												<th align="left"><?php echo $row['mother_job'];?></th>
												<th ><?php echo $row['mother_phone'];?></th>	
												
												<th align="left"><?php echo $row['guardian_name'];?></th>
												<th align="left"><?php echo $row['guardian_job'];?></th>
												<th ><?php echo $row['guardian_tel'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
		</div>
	</div>