<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Group'); 
	echo $this->headTitle(''); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<select dojoType="dijit.form.FilteringSelect" id="searchby" name="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Group Code</option>
			<option value="2">Room Name</option>
			<option value="3">Session</option>
			<option value="4">Grade</option>
		</select>
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
	<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
										<strong></strong><br />
										<strong></strong><br />
									</td>
								</tr>
								<tr>
									<td width="28%" >
										<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏  ក្រុមសិស្ស</strong><br />
										<strong></strong><br />
									</td>
									<td width="28%" align="right">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}
	
</style>
								<tr>
									<td colspan="3">
										<table cellpadding="3"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th >ល.រ</th>
												<th >Group Code</th>
												<th >Room Name</th>
												<th>Academic</th>
												<th >Semester</th>
												<th >Session</th>
												<th >Degree</th>
												<th >Grade</th>
												<th >Amount Mount</th>
												<th >Start Date</th>					
												<th >Expired Date</th>
												<th >Note</th>
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['group_code'];?></th>
												<th align="left">&nbsp;&nbsp;<?php echo $row['room_name'];?></th>
												<th ><?php echo $row['academic'];?></th>	
												<th ><?php echo $row['semester'];?></th>
												<th ><?php echo $row['session'];?></th>
												<th align="left">&nbsp;&nbsp;<?php echo $row['degree'];?></th>
												<th align="left">&nbsp;&nbsp;<?php echo $row['grade'];?></th>
												<th ><?php echo $row['amount_month'];?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['start_date']));?></th>					
												<th ><?php echo date("d-M-Y",strtotime($row['expired_date']));?></th>
												<th align="left"><?php echo $row['note'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
		</div>
	</div>