<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	echo $this->headTitle('SRMS | Student Exam Fundation Year'); 
	
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-info')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<select dojoType="dijit.form.FilteringSelect" id="searchby" name="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Kh Name</option>
			<option value="2">Eng Name</option>
		</select>
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>	
<div style="border: 1px dotted #000;background: #fff;">
		<div id="divPrint">
					<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
							<tr style="font-size: 13px;">
										<td colspan="3" align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
										</td>
								</tr>
								<tr>
										<td>&nbsp;</td>
								</tr>
								<tr>
										<td align="left" width="20%" >
											<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
										</td>
										<td align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">បញ្ជីពត៌មានសិស្ស</strong><br />
										</td>
										<td align="right" width="20%">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
										</td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th rowspan="2">ល.រ</th>
												<th rowspan="2">អត្តលេខ</th>	
												<th rowspan="2">ឈ្មោះ</th>
												<th rowspan="2">ឈ្មោះជាអក្សរឡាតាំង</th>
												<th rowspan="2">ភេទ</th>												
												<th rowspan="2">សញ្ចាតិ</th>
												<th rowspan="2" style="white-space: nowrap;">ថ្ងៃខែឆ្នាំកំណើត</th>
												<th rowspan="2">ទីកន្លែងកំណើត</th>
												<th colspan="3">លេខទូរសព្ទ</th>
												<th rowspan="2">អ៊ីម៉ែល</th>
												<th rowspan="2">ឈ្មោះ​​ឪពុក</th>
												<th rowspan="2">ឈ្មោះឪពុកជាអក្សរឡាតាំង</th>
												<th rowspan="2">សញ្ចាតិ</th>
												<th rowspan="2">មុខរបរ</th>
												<th rowspan="2">ឈ្មោះម្ដាយ</th>
												<th rowspan="2">ឈ្មោះម្ដាយជាអក្សរឡាតាំង</th>
												<th rowspan="2">សញ្ចាតិ</th>
												<th rowspan="2">មុខរបរ</th>
												<th rowspan="2">ឈ្មោះអណព្យាបាល</th>
												<th rowspan="2">ឈ្មោះអណព្យាបាលជាអក្សរឡាតាំង</th>
												<th rowspan="2">សញ្ចាតិ</th>
												<th rowspan="2">មុខរបរ</th>
												<th rowspan="2">លេខអត្តសញ្ញាណប័ណ្ណ /លិខិតឆ្លងដែន</th>
												<th rowspan="2">លេខទូរសព្ទ</th>
												<th rowspan="2">អ៊ីម៉ែល</th>
												<th rowspan="2">អាសយដ្ឋានរបស់និស្សិត</th>
												<th rowspan="2">ផ្សេងៗ</th>
											</tr>
											<tr​​>
												<th align="center"​​><small>Personal</small></th>
												<th align="center"><small>Father</small></th>
												<th align="center"><small>mother</small></th>
											</tr><style> td{padding:0 3px; }</style>
											<?php  $i=0; foreach ($this->rs as $row){ $i++;?>
											<tr style="font-size:13px;height: 23px;"​ align="center">
												<td><?php echo $i;?></td>
												<td style="white-space: nowrap;"><?php echo $row['stu_code'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_khname'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_enname'];?></td>
												<td><?php echo $row['gender'];?></td>
												<td><?php echo $row['nationality'];?></td>
												<td><?php echo $row['dob'];?></td>
												<td><?php echo $row['address'];?></td>
												<td><?php echo $row['tel'];?></td>
												<td><?php echo $row['father_phone'];?></td>
												<td><?php echo $row['mother_phone'];?></td>
												<td><?php echo $row['email'];?></td>
												<td><?php echo $row['father_khname'];?></td>
												<td><?php echo $row['father_enname'];?></td>
												<td><?php echo $row['father_nation'];?></td>
												<td><?php echo $row['far_job'];?></td>
												<td><?php echo $row['mother_khname'];?></td>
												<td><?php echo $row['mother_enname'];?></td>
												<td><?php echo $row['mother_nation'];?></td>
												<td><?php echo $row['mom_job'];?></td>
												<td><?php echo $row['guardian_khname'];?></td>
												<td><?php echo $row['guardian_enname'];?></td>
												<td><?php echo $row['guardian_nation'];?></td>
												<td><?php echo $row['guardian_document'];?></td>
												<td><?php  echo $row['guar_job'];?></td>
												<td><?php echo $row['guardian_tel'];?></td>
												<td><?php echo $row['guardian_email'];?></td>
												<td ><?php echo $row['home_num'];?> <?php echo $row['street_num'];?> <?php echo $row['village_name'];?> <?php echo $row['commune_name'];?> <?php  echo $row['pro'];?></td>
												<td><?php echo $row['remark'];?></td>
											</tr>
											<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
		</div>
	</div>
							