<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	$this->headTitle('SRMS | Report Static Student By Year'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	print_r($this->rows_sub);
?>	
<form  id='rpt_static_student' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'report','action'=>'rpt-static-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
							<strong align="center"><?php echo $tr->translate("");?></strong> 
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
							<?php if(!empty($this->rows_sub)) foreach($this->rows_sub As $key=>$rs_sub){$key=$key+1;?>
								<tr style="font-size: 18px;">
									<td colspan="2"></td>
									<td align="center">
										<strong>ស្ថិតិនិស្សិត ជំនាន់ទី១១ ឆ្នាំទី១ ថ្នាក់បរិញ្ញាបត្រ ឆ្នាំសិក្សា ២០១៣-១៤ ចុះឈ្មោះលើកទី១</strong><br /><br />
				
									</td>
								</tr>
								<tr>
									<td colspan="4" align="right"><strong><?php echo $key." . ".$rs_sub['subject_titleen']?></strong>
									
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:14px; height: 30px;" align="center" >
											<style> th{border-top:double;}</style>
												<th>Session</th>
												<th>English</th>
												<th>Hotel</th>
												<th>Law</th>	
												<th>Business</th>
												<th>Economics</th>
												<th>Computer</th>				
											</tr>
											<?php for ($i=1;$i<5;$i++){?>
											<tr style="font-size:12px;"​ align="center">
												<td>Morning</td>
												<td>82</td>
												<td>51</td>
												<td>0</td>
												<td>89</td>
												<td>129</td>
												<td>42</td>
											</tr>
											<?php }?>
											 	
										</table>
								   
									</td>
								</tr>
						 <?php }?>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</form>
