<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Group'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px;">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
								<td width="20%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><u>បញ្ជីរាយឈ្មោះក្រុម</u></strong><br >
								</td>
								<td align="right" width="20%">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
/* 											body{font-family: "Times New Roman",Arial; } */
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
/* 											.padd tr td{  text-align:center} */
											.padd tr th{  background-color: #ccc; }
										</style>

									<table cellpadding="3" class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										  <tr style="font-size:11px; height: 20px;" align="center">
										    <th>ល.រ</th>
										    <th>&nbsp;Group Code&nbsp;</th>
										    <th>&nbsp;Academic&nbsp;</th>
											<th>&nbsp;Semester&nbsp;</th>
											<th>&nbsp;Degree&nbsp;</th>
											<th>&nbsp;Grade&nbsp;</th>
											<th>&nbsp;Session&nbsp;</th>
											<th>&nbsp;Room&nbsp;</th>
											<th>&nbsp;Start Date&nbsp;</th>
											<th>&nbsp;End Date&nbsp;</th>
											<th>&nbsp;Note&nbsp;</th>
											<th>&nbsp;Student Amount&nbsp;</th>
										  </tr>
										  <tr></tr>
												
										  <?php $i=0; if (!empty($this->rs))foreach($this->rs as $rs){ $i++;?>
										  <tr style="font-size:10px; height: 18px;"​ align="center">
										    <td><?php echo $i;?></td>
										    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'foundation','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="blank"><?php echo $rs['group_code']; ?></a></td>
										    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'foundation','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="blank"><?php echo $rs['academic']; ?></a></td>
										    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'foundation','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="blank"><?php echo $rs['semester']; ?></a></td>
										    <td align="left">&nbsp;&nbsp;<?php echo $rs['degree']; ?></td>
										    <td><?php echo $rs['grade']; ?></td>
										    <td><?php echo $rs['session']; ?></td>
										    <td align="left">&nbsp;&nbsp;<?php echo $rs['room_name']; ?></td>
										    <td><?php echo $rs['start_date']; ?></td>
										    <td><?php echo $rs['expired_date']; ?></td>
										    <td align="left">&nbsp;&nbsp;<?php echo $rs['note']; ?></td>
										    <td><?php echo $rs['Num_Student']; ?></td>
										  </tr>
										  <?php } ?>
										</table>
									
									</td>
								</tr>
							</table>
	</div>	
</div>