<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_SCORE"));
	$frm =  $this->form_search;
?>	
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
	//control study year
		var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->g_all_name));?> );
		new dijit.form.FilteringSelect({
		    store:group_store,
		    autoComplete: true,                        
		    required:false,
		    id: "group_name",
		    name: "group_name",
		    class:'fullside',  
		    value:'<?php echo $this->g_name['group_name'];?>',         
		    required:'true',
		    placeHolder:"Selected Group Name",          
		    onChange: function() {  
		    	//getGroupName();
		    }
		}, "group_name");
});
</script>
<form  action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentscore','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:90%">
	  <tr> 
		<td><input id="group_name" /></td>
							   <td> <?php echo $frm->getElement("study_year");?></td>
							   <td> <?php echo $frm->getElement("grade");?></td>
							   <td> <?php echo $frm->getElement("session");?></td>
							   <td> <?php echo $frm->getElement("time");?></td>
	  </tr>
	  <tr>
	  	<td> <input dojoType="dijit.form.DateTextBox" class="fullside" id="start_date" name="start_date" value="<?php  if(empty($this->adv_search['start_date'])){echo date('Y-m-d');}else   echo $this->adv_search['start_date']; ?>"  type="text"></td>
 		<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" value="<?php if(empty($this->adv_search['end_date'])){ echo date('Y-m-d');}else echo $this->adv_search['end_date'];?>" type="text"></td>
		<td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	  </tr>
	 </table>
</form>
<?php 

  echo $this->list;
?>
