<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Group'); 
	echo $this->headTitle(''); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'lecturer','action'=>'rpt-lecturer')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<select dojoType="dijit.form.FilteringSelect" id="searchby" name="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Group Code</option>
			<option value="2">Room Name</option>
			<option value="3">Session</option>
			<option value="4">Grade</option>
		</select>
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
	<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
										<strong></strong><br />
										<strong></strong><br />
									</td>
								</tr>
								<tr>
									<td width="200px" >
										<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏  ក្រុមសិស្ស</strong><br />
										<strong></strong><br />
									</td>
									<td width="28%" align="right">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
									</td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th >ល.រ</th>
												<th >Teacher Code</th>
												<th >Teacher Name</th>
												<th>Sex</th>
												<th >Nationality</th>
												<th >Tel</th>
												<th >Email</th>
												<th >Degree</th>
												<th >Date Of Birth</th>
												<th >Address</th>
												<th >ID CARD No.</th>					
												<th >Passport ID</th>
												
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['teacher_code'];?></th>
												<th align="left"><?php echo $row['name'];?></th>
												<th ><?php echo $row['sex'];?></th>	
												<th ><?php echo $row['nationality'];?></th>
												<th ><?php echo $row['tel'];?></th>
												<th align="left"><?php echo $row['email'];?></th>
												<th align="left"><?php echo $row['degree'];?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['dob']));?></th>
												<th ><?php echo $row['address'];?></th>					
												<th ><?php echo $row['id_card_no'];?></th>
												<th align="left"><?php echo $row['pars_id'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
		</div>
	</div>