<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("FEE"));
?>	
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	dojo.require('dojox.form.BusyButton');
	var aca_year= getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_year));?> );
	var session  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_session));?> );
	var grade= getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_grade));?> );
	dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    store: aca_year,
	    autoComplete: true,                        
	    required: false,
	    id: "year",
	    name: "year",           
	    class: 'fullside',  
	    placeHolder:"Selected Acdemice Year",          
	    onChange: function() {  
	    	 
	    }
	}, "year");
	dijit.byId('year').attr('value','<?php echo $this->row_ace['year']?>');
/*	new dijit.form.FilteringSelect({
	    store: session,
	    autoComplete: true,                        
	    required: false,
	    id: "session",
	    name: "session",           
	    class: 'fullside',  
	    placeHolder:"Selected Session",          
	    onChange: function() {  
	    	 
	    }
	}, "session");
	new dijit.form.FilteringSelect({
	    store: grade,
	    autoComplete: true,                        
	    required: false,
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	 
	    }
	}, "grade");
	*/
});
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:40%" style="width:100px;">
	  <tr> 
		<td ><input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->adv_search['txtsearch']; ?>" type="text"></td>
		<td><input id="year" /></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	    <td></td>
	     <td></td>
	  </tr>
	</table>
</form>
<?php echo $this->list; ?>

 