<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("FEE"));
	$frm =  $this->form_search;
?>	

<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:90%" style="width:100px;">
						<tr> 
							  <td ><input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->adv_search['txtsearch']; ?>" type="text" class="fullside"></td>
							   <td> <?php echo $frm->getElement("study_year");?></td>
							   <td> <?php echo $frm->getElement("grade");?></td>
							   <td> <?php echo $frm->getElement("session");?></td>
							   <td> <?php echo $frm->getElement("time");?></td>
					   	  </tr>
					   	  <tr>
					   	     <td> <?php echo $frm->getElement("start_date");?></td>
							 <td> <?php echo $frm->getElement("end_date");?></td>
							 <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
	</table>
</form>
<?php echo $this->list; ?>

 