<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->headTitle($tr->translate("SRMS_ADD_GROUP"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();

?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'edit')); ?>" 
dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                major = dijit.byId('major').get('value');
                room = dijit.byId('room').get('value');

				if (major=='' || major==-1){
					alert('Please Select Faculty !');
                    dijit.byId('major').focus();
			        return false;
                }
               if (room=='' || room==-1){
					alert('Please Select room !');
                    dijit.byId('room').focus();
			        return false;
                }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%">
	<tr>
		<td>
				<fieldset style="margin-top:-13px;">
					<legend align="center" ><strong><?php echo $tr->translate("Group Faculty");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td width="110px"><?php echo $tr->translate("Group Code")?><input type="hidden" name="id" value="<?php echo $this->rs['id'];?>" /></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="group_code" name="group_code" value="<?php echo $this->rs['group_code'];?>" type="text"></td>
						    
						    <td width="110px"><?php echo $tr->translate("YEARS")?></td>
							<td>
								<select name="from_year" id="from_year" type="text" dojoType="dijit.form.FilteringSelect">
									<?php for($i=2014;$i<=date('Y')+1;$i++){?>
										<option value="<?php echo $i;?>" <?php if($i==$this->rs['from_academic']) echo 'selected="selected"';?> ><?php echo $i; ?></option>
									<?php }?>
							    </select>
							</td>
							
							<td width="110px"><?php echo $tr->translate("TO")?></td>
							<td>
								<select name="to_year" id="to_year" type="text" dojoType="dijit.form.FilteringSelect">
									<?php for($i=2014;$i<=date('Y')+2;$i++){?>
										<option value="<?php echo $i;?>" <?php if($i==$this->rs['to_academic']) echo 'selected="selected"';?> ><?php echo $i; ?></option>
									<?php }?>
							    </select>
							</td>
							
						</tr>
						<tr>
							<td><?php echo $tr->translate("Semester")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" name="semester" value="<?php echo $this->rs['semester'];?>" type="text"></td>
							<td><?php echo $tr->translate("Session")?></td>
							<td>
								<select name="session" id="session" dojoType="dijit.form.FilteringSelect">
								<?php $row=Application_Model_DbTable_DbGlobal::getSessionById();
									foreach($row as $key =>$rs){?>
										<option value="<?php echo $key;?>"<?php if($key==$this->rs['session']) echo 'selected="selected"';?> ><?php echo $rs;?></option>
								<?php 	}
								?>
								</select>
							</td>
							<td ><?php echo $tr->translate("DEGREE")?></td>
							<td>
								<select   name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
										<?php 
										if(!empty($this->degree))foreach ($this->degree as $row){?>
										<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->rs['degree']) echo 'selected="selected"';?> ><?php echo $row['en_name']?></option>
										<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("GRADE")?></td>
							<td width="100px">
								<input id="grade" name="grade" value="<?php echo $this->rs['grade']; ?>" />
							</td>
							
							
							<td><?php echo $tr->translate("ROOM")?></td>
							<td>
								<select   name="room" id="room" dojoType="dijit.form.FilteringSelect" >
										<?php 
											if(!empty($this->room))foreach ($this->room as $_row){?>
											<option value="<?php echo $_row['id']?>"<?php if($_row['id']==$this->rs['room_id']) echo 'selected="selected"';?>"><?php echo $_row['name']?></option>
										<?php }?>
								</select>
							
							</td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("Start Date")?></td>
							<td><input dojoType="dijit.form.DateTextBox" name="start_date" id="start_date" onchange="setEndDate();" value="<?php echo $this->rs['start_date'];?>" type="text"></td>
							<td><?php echo $tr->translate("Amount Month")?></td>
							<td><input dojoType="dijit.form.NumberTextBox"   name="amountmonth" id="amountmonth" value="<?php echo $this->rs['amount_month'];?>" onkeyup="setEndDate();" type="text"></td>
							<td style="width: 5px"><?php echo $tr->translate("End Date")?></td>
							<td><input dojoType="dijit.form.DateTextBox" id="end_date" name="end_date" type="text" readonly="readonly" value="<?php echo $this->rs['expired_date'];?>" ></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect">
								    <option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>>ប្រើប្រាស់</option>
								    <option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>>មិនប្រើប្រាស់</option>
								</select>
							</td>
							<td style="width: 5px"><?php echo $tr->translate("Note")?></td>
							<td><input dojoType="dijit.form.TextBox"   name="note" value="<?php echo $this->rs['note'];?>" type="text"></td>
						</tr>
						<tr>
							<td align="center" colspan="6">
									<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
									<div  id="test"></div>
				    	<tr>	
						<tr>
							<td colspan="6" align="center">
								<input type="submit" value="save" name="save" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>
</table>
</form>
<?php 
$techer= $this->frm_techer;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.date.locale");

dojo.require("dojo.html");
var room_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->room));?> );
dojo.ready(function(){
	

			new dijit.form.FilteringSelect({
			    autoComplete: true,                        
			    id: "grade",
			    name: "grade",           
			    class: 'fullside',  
			    placeHolder:"Selected Grade",          
			    onChange: function() {  
			    	make_id = dijit.byId('grade').get('value');
			    	//paymentTerm();
			    }
			}, "grade");
			getallGrade();
	
		
	});
function setEndDate(){
	amount_date = dijit.byId('amountmonth').get('value');
	release_date = dijit.byId("start_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
    }
}

var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   
			    dijit.byId('grade').attr('value',<?php echo $this->rs['grade'];?>);   
			    

			},
			error: function(err) {
				alert(err);
			}
		});
}


var url_room = '<?php echo $this->url(array('module'=>'global','controller'=>'room','action'=>'addroom')); ?>';
function addNewRoom(){
	if(dijit.byId('form_room').validate()){
		subject_id
		dojo.xhrPost({
			url:url_room,
			form: dojo.byId("form_room"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('classname').get('value')
				};			
				addDataToSelectbox(dijit.byId('room'), room_store, myNewItem, data);
				dijit.byId('form_room').reset();
				dijit.byId("pop_room").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
</script>